# Very messy, sorry, probably going to discard these

# Old

In [71]:
swings_and_volatility['Adjusted volatility score'] = (
    swings_and_volatility['Volatility'] + 
    swings_and_volatility['2016-2020 absolute swing'] + 
    swings_and_volatility['Volatility minus absolute change'] +
    (swings_and_volatility['Volatility div absolute change'] / 100) +
    swings_and_volatility['Average 3P % (± national avg)'] + 
    swings_and_volatility['Max 3P % (± national avg)'] - 
    swings_and_volatility['Min 3P % (± national avg)'] - 
    swings_and_volatility['3P% Total Effect of Extremes'] -
    swings_and_volatility['2P Total Effect of Extremes'] +
    abs(swings_and_volatility['2000-2020 D-R net swing'])
)

In [72]:
swings_and_volatility.nlargest(10, 'Adjusted volatility score')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 D-R swing,2000-2004 D-R swing ± Natl. Avg,...,Largest 2P Swing ± Natl. Average,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Absolute Effect of Largest Outlier,2P Absolute Effect of Smallest Outlier,2P Total Effect of Extremes,Adjusted volatility score,Abrupt Reversion Penalty,Adjusted volatility score (targeted)
2705,Starr County,Texas,54.276938,47.510480,69.260621,73.323235,60.178876,4.998573,-6.766458,-2.352180,...,34.999527,-16.118161,0.532674,0.742495,19.648101,19.438280,39.086381,213.076916,5.755170,139.786318
2748,Cache County,Utah,-62.609378,-65.719463,-45.565180,-68.084553,-27.246138,-36.639364,-3.110086,1.304193,...,21.635338,-16.092991,4.338391,10.208594,14.864686,8.994483,23.859169,207.726650,93.844886,51.150059
2650,Maverick County,Texas,30.902590,19.164840,57.025322,58.051690,55.791875,9.455233,-11.737750,-7.323472,...,26.492431,-18.817844,0.786793,1.141546,19.057419,18.702665,37.760084,202.955381,1.923385,156.687477
552,Madison County,Idaho,-79.431438,-84.789894,-72.788543,-87.517347,-49.337073,-63.657083,-5.358456,-0.944178,...,21.262495,-11.559323,2.359753,8.393426,14.558026,8.524353,23.082379,189.686669,87.085649,62.734194
2770,Utah County,Utah,-68.029870,-74.351257,-58.912506,-78.592450,-36.546581,-41.077999,-6.321387,-1.907109,...,24.442395,-13.072056,3.575620,9.519501,14.027853,8.083973,22.111826,187.550554,62.190566,65.584691
2751,Davis County,Utah,-51.824028,-59.755830,-42.257128,-61.925018,-24.162097,-27.514810,-7.931801,-3.517523,...,20.520115,-13.890092,3.368656,9.164987,13.874149,8.077818,21.951968,181.904388,58.889024,63.407981
2760,Morgan County,Utah,-60.264901,-73.652695,-63.013699,-80.726561,-50.288906,-61.989101,-13.387794,-8.973515,...,13.662154,-6.136504,3.473622,7.944201,13.301878,8.831300,22.133178,179.535407,89.804384,67.086802
2768,Tooele County,Utah,-30.496795,-48.313730,-29.809079,-50.589274,-30.216684,-38.313337,-17.816935,-13.402657,...,3.665990,-9.017552,3.558074,8.058135,13.556131,9.056070,22.612201,178.592762,96.486918,34.814389
2744,Zapata County,Texas,26.185015,14.975845,35.589672,43.183743,32.908975,-5.343314,-11.209170,-6.794891,...,20.663465,-9.994754,0.486862,0.697877,17.101963,16.890948,33.992911,174.928455,19.364409,108.234941
1977,Grant County,North Dakota,-59.004905,-55.394525,-23.100075,-48.903043,-66.835626,-67.921796,3.610380,8.024659,...,16.149140,-15.059141,4.489208,9.830031,11.656102,6.315279,17.971381,174.499734,0.000000,111.204415

In [61]:
swings_and_volatility[swings_and_volatility['County'].str.contains('Bayfield')]

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 D-R swing,2000-2004 D-R swing ± Natl. Avg,...,Smallest 2P Absolute Swing,Largest Minus Smallest 2P Swing,Largest 2P Swing ± Natl. Average,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Absolute Effect of Largest Outlier,2P Absolute Effect of Smallest Outlier,2P Total Effect of Extremes,Adjusted volatility score
3019,Bayfield County,Wisconsin,14.057392,21.558924,27.534854,24.826318,8.699759,14.0625,7.501532,11.91581,...,2.708536,13.418023,8.591499,-4.826524,1.951233,3.011275,5.583827,4.523785,10.107611,144.865122

# Volatility old

In [48]:
swings_and_volatility['Adjusted volatility score'] = (
    swings_and_volatility['Volatility'] + 
    swings_and_volatility['2016-2020 absolute swing'] + 
    swings_and_volatility['Volatility minus absolute change'] +
    (swings_and_volatility['Volatility div absolute change'] / 100) +
    swings_and_volatility['Average 3P % (± national avg)'] + 
    swings_and_volatility['Max 3P % (± national avg)'] + 
    swings_and_volatility['Min 3P % (± national avg)'] -
    (swings_and_volatility['3P% Total Effect of Extremes'] ** 2) -
    swings_and_volatility['Largest 2P Absolute Swing']
)

In [49]:
swings_and_volatility.nlargest(10, 'Adjusted volatility score')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 D-R swing,2000-2004 D-R swing ± Natl. Avg,...,Smallest 2P Absolute Swing,Largest Minus Smallest 2P Swing,Largest 2P Swing ± Natl. Average,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Absolute Effect of Largest Outlier,2P Absolute Effect of Smallest Outlier,2P Total Effect of Extremes,Adjusted volatility score
2650,Maverick County,Texas,30.902590,19.164840,57.025322,58.051690,55.791875,9.455233,-11.737750,-7.323472,...,1.026368,45.310275,26.492431,-18.817844,0.786793,1.141546,19.057419,18.702665,37.760084,172.567598
2768,Tooele County,Utah,-30.496795,-48.313730,-29.809079,-50.589274,-30.216684,-38.313337,-17.816935,-13.402657,...,8.096653,12.683542,3.665990,-9.017552,3.558074,8.058135,13.556131,9.056070,22.612201,159.285775
2760,Morgan County,Utah,-60.264901,-73.652695,-63.013699,-80.726561,-50.288906,-61.989101,-13.387794,-8.973515,...,10.638996,19.798659,13.662154,-6.136504,3.473622,7.944201,13.301878,8.831300,22.133178,155.663130
1961,Benson County,North Dakota,-4.781801,8.637578,33.529907,17.014372,-4.326206,-13.870474,13.419379,17.833658,...,9.544268,15.348061,7.749911,-7.598150,3.021561,4.907738,14.120857,12.234680,26.355537,152.482495
2747,Box Elder County,Utah,-62.862494,-73.535497,-62.530171,-77.890561,-50.407905,-63.186915,-10.673002,-6.258724,...,10.673002,16.809654,12.022579,-4.787074,2.851950,7.318371,12.608126,8.141705,20.749832,148.093090
2705,Starr County,Texas,54.276938,47.510480,69.260621,73.323235,60.178876,4.998573,-6.766458,-2.352180,...,4.062614,51.117688,34.999527,-16.118161,0.532674,0.742495,19.648101,19.438280,39.086381,146.618059
2765,Sanpete County,Utah,-61.507402,-68.355472,-57.382283,-77.783597,-55.214482,-68.633663,-6.848070,-2.433791,...,6.848070,15.721045,7.726941,-7.994104,3.929200,7.531778,10.912973,7.310395,18.223369,143.293482
2004,Steele County,North Dakota,-14.876033,2.473207,20.348837,1.919386,-17.717718,-23.897059,17.349240,21.763518,...,6.179341,13.457762,3.742950,-9.714812,3.082864,4.276043,12.811289,11.618111,24.429400,141.450486
3019,Bayfield County,Wisconsin,14.057392,21.558924,27.534854,24.826318,8.699759,14.062500,7.501532,11.915810,...,2.708536,13.418023,8.591499,-4.826524,1.951233,3.011275,5.583827,4.523785,10.107611,139.035960
2748,Cache County,Utah,-62.609378,-65.719463,-45.565180,-68.084553,-27.246138,-36.639364,-3.110086,1.304193,...,3.110086,37.728329,21.635338,-16.092991,4.338391,10.208594,14.864686,8.994483,23.859169,138.759130

In [53]:
swings_and_volatility.nsmallest(10, 'Adjusted volatility score')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,Average 2P Absolute Swing,Largest 2P Absolute Swing,Smallest 2P Absolute Swing,Largest Minus Smallest 2P Swing,Largest 2P Swing ± Natl. Average,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Net Effect of Outliers,Adjusted volatility score
1021,Knott County,Kentucky,35.924435,27.549364,-7.869416,-47.602319,-53.999653,-53.863382,-8.375070,8.375070,...,18.012072,39.732903,0.136271,39.596632,21.720831,-17.875801,1.581321,1.892303,-0.310982,-42.567088
1474,Clark County,Missouri,-2.288269,-2.810493,-6.076389,-10.294574,-53.934681,-58.750737,-0.522223,0.522223,...,11.292493,43.640108,0.522223,43.117884,32.347614,-10.770270,1.763735,1.886590,-0.122855,-41.724868
2963,Boone County,West Virginia,25.194180,16.924887,10.716846,-31.494118,-54.289992,-52.984909,-8.269293,8.269293,...,16.157851,42.210964,1.305083,40.905881,26.053113,-14.852768,1.817710,2.214311,-0.396601,-37.436869
2987,Mcdowell County,West Virginia,34.191428,23.825182,8.522551,-29.896574,-51.442850,-58.449517,-10.366247,10.366247,...,18.528189,38.419125,7.006667,31.412457,19.890935,-11.521522,1.635574,1.432971,0.202602,-36.143538
997,Floyd County,Kentucky,32.610108,25.272575,-1.347468,-33.922095,-48.234583,-51.165066,-7.337533,7.337533,...,16.755035,32.574627,2.930484,29.644144,15.819593,-13.824551,1.728882,2.062959,-0.334078,-32.595047
3015,Wyoming County,West Virginia,10.357959,-14.808442,-25.046481,-55.642696,-70.042140,-72.113594,-25.166401,25.166401,...,16.494311,30.596215,2.071454,28.524761,14.101904,-14.422857,1.969101,1.764080,0.205021,-32.439310
2990,Mingo County,West Virginia,21.736533,12.867198,-12.053250,-42.616082,-68.780231,-71.313111,-8.869334,8.869334,...,18.609929,30.562831,2.532880,28.029952,11.952903,-16.077049,1.781436,1.639155,0.142281,-32.370985
63,Walker County,Alabama,-7.273507,-35.784538,-46.426078,-52.922408,-67.077226,-67.911453,-28.511031,28.511031,...,12.127589,28.511031,0.834227,27.676804,16.383442,-11.293362,1.336041,1.461179,-0.125139,-31.982645
2983,Logan County,West Virginia,24.883995,5.538133,-10.790939,-39.787377,-63.152359,-62.958698,-19.345862,19.345862,...,17.646003,28.996437,0.193661,28.802776,11.350434,-17.452342,1.396774,1.600430,-0.203656,-31.879963
1059,Pike County,Kentucky,10.451173,5.196115,-13.823257,-50.533085,-62.708291,-60.773415,-5.255058,5.255058,...,15.018868,36.709828,1.934876,34.774953,21.690961,-13.083992,1.299550,1.478415,-0.178866,-31.231205

In [55]:
swings_and_volatility['Adjusted volatility score v2'] = (
    swings_and_volatility['Volatility'] + 
    swings_and_volatility['2016-2020 absolute swing'] + 
    swings_and_volatility['Volatility minus absolute change'] +
    (swings_and_volatility['Volatility div absolute change'] / 100) +
    swings_and_volatility['Average 3P % (± national avg)'] + 
    swings_and_volatility['Max 3P % (± national avg)'] + 
    swings_and_volatility['Min 3P % (± national avg)'] +
    swings_and_volatility['3P% Total Effect of Extremes'] +
    swings_and_volatility['2P Net Effect of Outliers']
)

In [56]:
swings_and_volatility['V1 vs V2'] = swings_and_volatility['Adjusted volatility score v2'] - swings_and_volatility['Adjusted volatility score']

In [57]:
swings_and_volatility.nlargest(5, 'V1 vs V2')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,Smallest 2P Absolute Swing,Largest Minus Smallest 2P Swing,Largest 2P Swing ± Natl. Average,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Net Effect of Outliers,Adjusted volatility score,Adjusted volatility score v2,V1 vs V2
2987,Mcdowell County,West Virginia,34.191428,23.825182,8.522551,-29.896574,-51.442850,-58.449517,-10.366247,10.366247,...,7.006667,31.412457,19.890935,-11.521522,1.635574,1.432971,0.202602,-36.143538,95.362785,131.506323
2427,Grundy County,Tennessee,30.831158,13.914280,-12.780656,-20.604201,-55.364266,-65.140905,-16.916878,16.916878,...,7.823545,26.936520,15.565653,-11.370868,1.469156,1.688964,-0.219809,-28.802451,101.977993,130.780444
1021,Knott County,Kentucky,35.924435,27.549364,-7.869416,-47.602319,-53.999653,-53.863382,-8.375070,8.375070,...,0.136271,39.596632,21.720831,-17.875801,1.581321,1.892303,-0.310982,-42.567088,87.050341,129.617429
2440,Jackson County,Tennessee,40.387042,19.239905,0.866474,-15.391969,-47.178683,-56.039827,-21.147138,21.147138,...,8.861144,22.925570,12.501340,-10.424230,1.698142,1.528457,0.169685,-27.365167,101.237635,128.602802
993,Elliott County,Kentucky,29.315414,40.344944,25.168986,2.501042,-44.133100,-51.218698,11.029531,11.029531,...,7.085598,39.548544,26.115507,-13.433037,1.985054,2.170379,-0.185326,2.603282,130.327555,127.724273

In [59]:
swings_and_volatility.nlargest(10, 'Largest Minus Smallest 2P Swing')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,Smallest 2P Absolute Swing,Largest Minus Smallest 2P Swing,Largest 2P Swing ± Natl. Average,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Net Effect of Outliers,Adjusted volatility score,Adjusted volatility score v2,V1 vs V2
2705,Starr County,Texas,54.276938,47.510480,69.260621,73.323235,60.178876,4.998573,-6.766458,6.766458,...,4.062614,51.117688,34.999527,-16.118161,0.532674,0.742495,-0.209822,97.339695,201.911801,104.572106
2650,Maverick County,Texas,30.902590,19.164840,57.025322,58.051690,55.791875,9.455233,-11.737750,11.737750,...,1.026368,45.310275,26.492431,-18.817844,0.786793,1.141546,-0.354753,151.120241,219.030091,67.909849
1474,Clark County,Missouri,-2.288269,-2.810493,-6.076389,-10.294574,-53.934681,-58.750737,-0.522223,0.522223,...,0.522223,43.117884,32.347614,-10.770270,1.763735,1.886590,-0.122855,-41.724868,58.631827,100.356695
2963,Boone County,West Virginia,25.194180,16.924887,10.716846,-31.494118,-54.289992,-52.984909,-8.269293,8.269293,...,1.305083,40.905881,26.053113,-14.852768,1.817710,2.214311,-0.396601,-37.436869,83.288337,120.725206
802,Howard County,Iowa,11.222445,12.476049,25.782572,20.947255,-20.486949,-27.450585,1.253604,1.253604,...,1.253604,40.180600,27.875547,-12.305053,1.712843,2.548632,-0.835789,23.689355,104.495133,80.805778
1021,Knott County,Kentucky,35.924435,27.549364,-7.869416,-47.602319,-53.999653,-53.863382,-8.375070,8.375070,...,0.136271,39.596632,21.720831,-17.875801,1.581321,1.892303,-0.310982,-42.567088,87.050341,129.617429
993,Elliott County,Kentucky,29.315414,40.344944,25.168986,2.501042,-44.133100,-51.218698,11.029531,11.029531,...,7.085598,39.548544,26.115507,-13.433037,1.985054,2.170379,-0.185326,2.603282,130.327555,127.724273
599,Henderson County,Illinois,8.329022,9.920539,17.671736,12.247758,-28.425242,-33.095695,1.591517,1.591517,...,1.591517,39.081482,28.650971,-10.430512,1.732957,2.553506,-0.820549,0.870721,83.641738,82.771017
2615,Jim Hogg County,Texas,41.214650,30.605327,47.603306,56.688662,56.866446,17.878193,-10.609323,10.609323,...,0.177784,38.810470,23.816515,-14.993955,0.547204,0.852892,-0.305687,99.839278,162.350257,62.510980
2067,Monroe County,Ohio,6.465214,10.596455,9.152105,-7.564140,-47.181751,-53.973139,4.131241,4.131241,...,1.444349,38.173261,25.877444,-12.295817,2.355518,2.794672,-0.439154,-16.606581,83.731787,100.338368

Maybe still included '2000-2020 absolute net swing' could still be included, if 'Largest minus smallest' is subtracted.

In [61]:
swings_and_volatility['Adjusted volatility score v3'] = (
    swings_and_volatility['Volatility'] + 
    swings_and_volatility['2016-2020 absolute swing'] + 
    swings_and_volatility['Volatility minus absolute change'] +
    (swings_and_volatility['Volatility div absolute change'] / 100) +
    swings_and_volatility['Average 3P % (± national avg)'] + 
    swings_and_volatility['Max 3P % (± national avg)'] + 
    swings_and_volatility['Min 3P % (± national avg)'] +
    swings_and_volatility['3P% Total Effect of Outliers'] +
    swings_and_volatility['2P Net Effect of Outliers'] -
    swings_and_volatility['Largest Minus Smallest 2P Swing']
)

In [62]:
swings_and_volatility['V1 vs V3'] = swings_and_volatility['Adjusted volatility score v3'] - swings_and_volatility['Adjusted volatility score']

In [63]:
swings_and_volatility

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,Largest 2P Swing ± Natl. Average,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Net Effect of Outliers,Adjusted volatility score,Adjusted volatility score v2,V1 vs V2,Adjusted volatility score v3,V1 vs V3
0,Autauga County,Alabama,-40.975128,-51.979483,-47.840616,-46.030420,-48.996917,-44.418437,-11.004355,11.004355,...,6.104676,-3.089483,1.034200,1.417982,-0.383782,32.259199,46.930679,14.671480,37.736520,5.477321
1,Baldwin County,Alabama,-47.583215,-53.912291,-51.447558,-55.768825,-57.160111,-53.762343,-6.329076,6.329076,...,2.748249,-2.189540,1.466952,1.996769,-0.529818,18.333908,31.122818,12.788910,26.185029,7.851121
2,Barbour County,Alabama,0.885041,-9.900714,-1.453138,3.145364,-5.568822,-7.663054,-10.785755,10.785755,...,3.857705,-4.833819,0.647946,0.770924,-0.122978,37.240342,56.589315,19.348974,47.897792,10.657450
3,Bibb County,Alabama,-22.010984,-44.513158,-45.846830,-46.674584,-55.153646,-57.727983,-22.502174,22.502174,...,15.358774,-6.315646,1.006387,1.271552,-0.265165,-24.728849,33.560636,58.289485,11.886217,36.615066
4,Blount County,Alabama,-42.786402,-62.537202,-69.505913,-74.093977,-80.909020,-80.002175,-19.750801,19.750801,...,11.944908,-6.899048,1.231174,1.385637,-0.154464,-19.594398,37.432275,57.026673,18.588320,38.182718
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,Sweetwater County,Wyoming,-24.880505,-33.462389,-27.315392,-39.384433,-52.089901,-50.341358,-8.581885,8.581885,...,4.455081,-6.501844,3.893627,4.981399,-1.087772,28.282375,67.631945,39.349570,56.675020,28.392645
3107,Teton County,Wyoming,-13.757070,7.465446,23.521320,11.819609,26.870991,37.242172,21.222516,21.222516,...,6.341983,-4.509352,4.315422,5.711403,-1.395981,43.963277,118.133797,74.170521,107.282463,63.319186
3108,Uinta County,Wyoming,-51.482879,-52.790496,-40.936089,-58.402623,-58.465171,-62.427318,-1.307617,1.307617,...,10.535883,-6.868103,3.546895,5.371208,-1.824313,42.375284,74.114375,31.739091,56.710389,14.335105
3109,Washakie County,Wyoming,-57.566033,-57.000486,-46.682927,-56.288032,-62.375459,-64.335317,0.565547,0.565547,...,4.610460,-5.141552,2.676909,3.932718,-1.255809,39.822329,58.486229,18.663900,48.734216,8.911887
3110,Weston County,Wyoming,-67.712418,-63.649764,-57.410662,-71.420065,-77.538287,-77.162921,4.062654,4.062654,...,7.848454,-5.785584,3.040249,3.449965,-0.409715,31.211964,54.841828,23.629863,41.207790,9.995825

In [64]:
swings_and_volatility['V2 vs V3'] = swings_and_volatility['Adjusted volatility score v3'] - swings_and_volatility['Adjusted volatility score v2']

In [65]:
swings_and_volatility.nsmallest(5, 'V1 vs V3')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Net Effect of Outliers,Adjusted volatility score,Adjusted volatility score v2,V1 vs V2,Adjusted volatility score v3,V1 vs V3,V2 vs V3
1449,Winston County,Mississippi,-11.627629,-15.082072,-8.282630,-5.707600,-11.935593,-11.606756,-3.454443,3.454443,...,-3.548312,0.592369,0.742968,-0.150599,35.168779,42.011774,6.842995,35.541169,0.372390,-6.470605
1393,Harrison County,Mississippi,-24.923977,-26.251416,-26.074833,-25.819543,-30.301834,-25.200612,-1.327438,1.327438,...,-2.091982,1.253601,1.497538,-0.243937,18.387619,23.880881,5.493262,18.956242,0.568623,-4.924639
2868,Mecklenburg County,Virginia,-15.471083,-15.852895,-4.574990,-6.977515,-13.402476,-15.197137,-0.381812,0.381812,...,-4.074561,1.300011,1.534926,-0.234915,31.298664,42.905700,11.607036,32.009607,0.710943,-10.896093
1437,Tallahatchie County,Mississippi,11.099040,10.582698,19.052434,22.451176,14.906303,10.853122,-0.516343,0.516343,...,-4.280232,0.859824,0.987937,-0.128113,38.252023,46.984090,8.732067,39.030696,0.778674,-7.953394
2717,Tom Green County,Texas,-44.605210,-51.254777,-41.697332,-47.886710,-47.612984,-44.401681,-6.649567,6.649567,...,-4.902558,1.234773,1.827137,-0.592364,44.223674,54.335544,10.111870,45.051825,0.828151,-9.283719

In [66]:
swings_and_volatility.nlargest(5, 'V1 vs V2')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Net Effect of Outliers,Adjusted volatility score,Adjusted volatility score v2,V1 vs V2,Adjusted volatility score v3,V1 vs V3,V2 vs V3
2987,Mcdowell County,West Virginia,34.191428,23.825182,8.522551,-29.896574,-51.442850,-58.449517,-10.366247,10.366247,...,-11.521522,1.635574,1.432971,0.202602,-36.143538,95.362785,131.506323,63.950327,100.093865,-31.412457
2427,Grundy County,Tennessee,30.831158,13.914280,-12.780656,-20.604201,-55.364266,-65.140905,-16.916878,16.916878,...,-11.370868,1.469156,1.688964,-0.219809,-28.802451,101.977993,130.780444,75.041473,103.843923,-26.936520
1021,Knott County,Kentucky,35.924435,27.549364,-7.869416,-47.602319,-53.999653,-53.863382,-8.375070,8.375070,...,-17.875801,1.581321,1.892303,-0.310982,-42.567088,87.050341,129.617429,47.453710,90.020798,-39.596632
2440,Jackson County,Tennessee,40.387042,19.239905,0.866474,-15.391969,-47.178683,-56.039827,-21.147138,21.147138,...,-10.424230,1.698142,1.528457,0.169685,-27.365167,101.237635,128.602802,78.312065,105.677232,-22.925570
993,Elliott County,Kentucky,29.315414,40.344944,25.168986,2.501042,-44.133100,-51.218698,11.029531,11.029531,...,-13.433037,1.985054,2.170379,-0.185326,2.603282,130.327555,127.724273,90.779011,88.175729,-39.548544

It is obvious that adding the raw '2000-2020 absolute net swing' is inflating the scores of counties which have merely changed loyalties over time, which is not the same thing as being susciptible to shifts in any given year. If it is included, it will have to be adjusted for something, maybe divided the average?

In [67]:
swings_and_volatility.nlargest(5, 'Adjusted volatility score v2')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Net Effect of Outliers,Adjusted volatility score,Adjusted volatility score v2,V1 vs V2,Adjusted volatility score v3,V1 vs V3,V2 vs V3
2650,Maverick County,Texas,30.902590,19.164840,57.025322,58.051690,55.791875,9.455233,-11.737750,11.737750,...,-18.817844,0.786793,1.141546,-0.354753,151.120241,219.030091,67.909849,173.719816,22.599574,-45.310275
2748,Cache County,Utah,-62.609378,-65.719463,-45.565180,-68.084553,-27.246138,-36.639364,-3.110086,3.110086,...,-16.092991,4.338391,10.208594,-5.870203,112.789116,214.056824,101.267708,176.328495,63.539379,-37.728329
2760,Morgan County,Utah,-60.264901,-73.652695,-63.013699,-80.726561,-50.288906,-61.989101,-13.387794,13.387794,...,-6.136504,3.473622,7.944201,-4.470579,153.938930,206.086858,52.147928,186.288199,32.349270,-19.798659
552,Madison County,Idaho,-79.431438,-84.789894,-72.788543,-87.517347,-49.337073,-63.657083,-5.358456,5.358456,...,-11.559323,2.359753,8.393426,-6.033673,112.733332,203.093169,90.359837,170.271351,57.538020,-32.821818
2705,Starr County,Texas,54.276938,47.510480,69.260621,73.323235,60.178876,4.998573,-6.766458,6.766458,...,-16.118161,0.532674,0.742495,-0.209822,97.339695,201.911801,104.572106,150.794113,53.454418,-51.117688

In [68]:
swings_and_volatility.nlargest(5, 'Adjusted volatility score v3')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Net Effect of Outliers,Adjusted volatility score,Adjusted volatility score v2,V1 vs V2,Adjusted volatility score v3,V1 vs V3,V2 vs V3
2768,Tooele County,Utah,-30.496795,-48.313730,-29.809079,-50.589274,-30.216684,-38.313337,-17.816935,17.816935,...,-9.017552,3.558074,8.058135,-4.500062,151.469232,200.316524,48.847292,187.632982,36.163750,-12.683542
2760,Morgan County,Utah,-60.264901,-73.652695,-63.013699,-80.726561,-50.288906,-61.989101,-13.387794,13.387794,...,-6.136504,3.473622,7.944201,-4.470579,153.938930,206.086858,52.147928,186.288199,32.349270,-19.798659
2747,Box Elder County,Utah,-62.862494,-73.535497,-62.530171,-77.890561,-50.407905,-63.186915,-10.673002,10.673002,...,-4.787074,2.851950,7.318371,-4.466421,147.768669,195.524661,47.755992,178.715007,30.946338,-16.809654
2748,Cache County,Utah,-62.609378,-65.719463,-45.565180,-68.084553,-27.246138,-36.639364,-3.110086,3.110086,...,-16.092991,4.338391,10.208594,-5.870203,112.789116,214.056824,101.267708,176.328495,63.539379,-37.728329
2650,Maverick County,Texas,30.902590,19.164840,57.025322,58.051690,55.791875,9.455233,-11.737750,11.737750,...,-18.817844,0.786793,1.141546,-0.354753,151.120241,219.030091,67.909849,173.719816,22.599574,-45.310275

In [69]:
swings_and_volatility.nsmallest(5, 'V1 vs V3')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Net Effect of Outliers,Adjusted volatility score,Adjusted volatility score v2,V1 vs V2,Adjusted volatility score v3,V1 vs V3,V2 vs V3
1449,Winston County,Mississippi,-11.627629,-15.082072,-8.282630,-5.707600,-11.935593,-11.606756,-3.454443,3.454443,...,-3.548312,0.592369,0.742968,-0.150599,35.168779,42.011774,6.842995,35.541169,0.372390,-6.470605
1393,Harrison County,Mississippi,-24.923977,-26.251416,-26.074833,-25.819543,-30.301834,-25.200612,-1.327438,1.327438,...,-2.091982,1.253601,1.497538,-0.243937,18.387619,23.880881,5.493262,18.956242,0.568623,-4.924639
2868,Mecklenburg County,Virginia,-15.471083,-15.852895,-4.574990,-6.977515,-13.402476,-15.197137,-0.381812,0.381812,...,-4.074561,1.300011,1.534926,-0.234915,31.298664,42.905700,11.607036,32.009607,0.710943,-10.896093
1437,Tallahatchie County,Mississippi,11.099040,10.582698,19.052434,22.451176,14.906303,10.853122,-0.516343,0.516343,...,-4.280232,0.859824,0.987937,-0.128113,38.252023,46.984090,8.732067,39.030696,0.778674,-7.953394
2717,Tom Green County,Texas,-44.605210,-51.254777,-41.697332,-47.886710,-47.612984,-44.401681,-6.649567,6.649567,...,-4.902558,1.234773,1.827137,-0.592364,44.223674,54.335544,10.111870,45.051825,0.828151,-9.283719

In [70]:
swings_and_volatility.nsmallest(5, 'V2 vs V3')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Net Effect of Outliers,Adjusted volatility score,Adjusted volatility score v2,V1 vs V2,Adjusted volatility score v3,V1 vs V3,V2 vs V3
2705,Starr County,Texas,54.276938,47.510480,69.260621,73.323235,60.178876,4.998573,-6.766458,6.766458,...,-16.118161,0.532674,0.742495,-0.209822,97.339695,201.911801,104.572106,150.794113,53.454418,-51.117688
2650,Maverick County,Texas,30.902590,19.164840,57.025322,58.051690,55.791875,9.455233,-11.737750,11.737750,...,-18.817844,0.786793,1.141546,-0.354753,151.120241,219.030091,67.909849,173.719816,22.599574,-45.310275
1474,Clark County,Missouri,-2.288269,-2.810493,-6.076389,-10.294574,-53.934681,-58.750737,-0.522223,0.522223,...,-10.770270,1.763735,1.886590,-0.122855,-41.724868,58.631827,100.356695,15.513943,57.238810,-43.117884
2963,Boone County,West Virginia,25.194180,16.924887,10.716846,-31.494118,-54.289992,-52.984909,-8.269293,8.269293,...,-14.852768,1.817710,2.214311,-0.396601,-37.436869,83.288337,120.725206,42.382457,79.819325,-40.905881
802,Howard County,Iowa,11.222445,12.476049,25.782572,20.947255,-20.486949,-27.450585,1.253604,1.253604,...,-12.305053,1.712843,2.548632,-0.835789,23.689355,104.495133,80.805778,64.314533,40.625177,-40.180600

In [71]:
swings_and_volatility.nlargest(5, 'V2 vs V3')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,Smallest 2P Swing ± Natl. Average,Average 2P Excl. Largest Outlier,Average 2P Excl. Smallest Outlier,2P Net Effect of Outliers,Adjusted volatility score,Adjusted volatility score v2,V1 vs V2,Adjusted volatility score v3,V1 vs V3,V2 vs V3
2578,Glasscock County,Texas,-85.639229,-83.302064,-80.789946,-83.391003,-85.927152,-87.595712,2.337166,2.337166,...,-0.662450,0.654049,1.076858,-0.422809,13.530843,18.267150,4.736307,17.334652,3.803810,-0.932498
3094,Fremont County,Wyoming,-41.362341,-35.628217,-28.602879,-33.898105,-40.926981,-35.581880,5.734124,5.734124,...,-0.790507,3.405909,4.429471,-1.023562,53.771753,67.815972,14.044219,66.082322,12.310569,-1.733650
2040,Greene County,Ohio,-19.764125,-22.513624,-18.418691,-21.036052,-23.940238,-19.487156,-2.749499,2.749499,...,-0.746451,1.771884,2.440776,-0.668893,32.585502,37.762970,5.177468,35.927249,3.341747,-1.835721
2323,Pickens County,South Carolina,-45.555491,-48.067144,-46.226290,-48.997783,-52.767641,-50.849755,-2.511653,2.511653,...,-0.721494,1.933580,2.372952,-0.439372,12.637066,22.193861,9.556796,20.264858,7.627792,-1.929004
2184,Curry County,Oregon,-21.375836,-16.501289,-11.482322,-16.895016,-23.090952,-16.254606,4.874547,4.874547,...,-0.793151,3.932792,4.896472,-0.963680,52.104472,64.990726,12.886254,63.028927,10.924455,-1.961799

In [72]:
swings_and_volatility['V1 vs V2'].mean()

np.float64(38.72886031206933)

In [73]:
swings_and_volatility['V2 vs V3'].mean()

np.float64(-14.648827366455413)

In [74]:
swings_and_volatility['V1 vs V3'].mean()

np.float64(24.080032945613922)

# V3A

In [62]:
# Penalize counties that swung hard one way, then reversed
swings_and_volatility['Reversion Penalty'] = (
    -np.minimum(
        abs(swings_and_volatility['2012-2016 swing']),
        abs(swings_and_volatility['2016-2020 swing'])
    ) * np.sign(
        swings_and_volatility['2012-2016 swing'] * swings_and_volatility['2016-2020 swing']
    )  # Only penalize if signs are opposite
)


swings_and_volatility['Adjusted volatility score v3a'] = (
    swings_and_volatility['Volatility'] + 
    swings_and_volatility['2016-2020 absolute swing'] + 
    swings_and_volatility['Volatility minus absolute change'] +
    (swings_and_volatility['Volatility div absolute change'] / 100) +
    swings_and_volatility['Average 3P % (± national avg)'] + 
    swings_and_volatility['Max 3P % (± national avg)'] + 
    swings_and_volatility['Min 3P % (± national avg)'] +
    swings_and_volatility['3P% Net Effect of Outliers'] +
    swings_and_volatility['2P Net Effect of Outliers'] -
    swings_and_volatility['Largest minus smallest'] +
    swings_and_volatility['Reversion Penalty']  # newly added mitigation
)

In [63]:
swings_and_volatility.nlargest(10, 'Adjusted volatility score v3a')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,Average 2P Excl. Smallest Outlier,2P Net Effect of Outliers,Adjusted volatility score,Adjusted volatility score v2,V1 vs V2,Adjusted volatility score v3,V1 vs V3,V2 vs V3,Reversion Penalty,Adjusted volatility score v3a
2760,Morgan County,Utah,-60.26,-73.65,-63.01,-80.72,-50.29,-61.99,-13.39,13.39,...,7.944,-4.470,207.788946,206.058946,-1.73,186.268946,-21.52,-19.79,11.70,197.968946
2768,Tooele County,Utah,-30.50,-48.32,-29.81,-50.59,-30.22,-38.31,-17.82,17.82,...,8.058,-4.500,208.120380,200.310380,-7.81,187.620380,-20.50,-12.69,8.09,195.710380
2747,Box Elder County,Utah,-62.86,-73.53,-62.53,-77.89,-50.41,-63.19,-10.67,10.67,...,7.318,-4.468,195.787936,195.457936,-0.33,178.647936,-17.14,-16.81,12.78,191.427936
2748,Cache County,Utah,-62.61,-65.71,-45.56,-68.09,-27.25,-36.64,-3.10,3.10,...,10.208,-5.870,240.012784,214.042784,-25.97,176.302784,-63.71,-37.74,9.39,185.692784
552,Madison County,Idaho,-79.43,-84.79,-72.79,-87.52,-49.33,-63.66,-5.36,5.36,...,8.392,-6.034,218.919467,203.149467,-15.77,170.319467,-48.60,-32.83,14.33,184.649467
2765,Sanpete County,Utah,-61.51,-68.35,-57.38,-77.78,-55.21,-68.63,-6.84,6.84,...,7.534,-3.602,185.955028,178.835028,-7.12,163.105028,-22.85,-15.73,13.42,176.525028
2650,Maverick County,Texas,30.90,19.17,57.03,58.05,55.80,9.45,-11.73,11.73,...,1.142,-0.354,240.472067,219.022067,-21.45,173.692067,-66.78,-45.33,-2.25,171.442067
2757,Juab County,Utah,-50.41,-60.75,-53.71,-75.46,-57.10,-75.73,-10.34,10.34,...,6.962,-3.286,192.335878,167.015878,-25.32,152.305878,-40.03,-14.71,18.36,170.665878
540,Franklin County,Idaho,-72.61,-80.55,-71.87,-86.97,-63.94,-77.85,-7.94,7.94,...,6.106,-3.518,171.823512,166.583512,-5.24,151.493512,-20.33,-15.09,13.91,165.403512
1977,Grant County,North Dakota,-59.00,-55.39,-23.10,-48.90,-66.83,-67.92,3.61,3.61,...,9.828,-5.340,200.172975,191.252975,-8.92,160.052975,-40.12,-31.20,-1.09,158.962975

# V3B

In [64]:
swings_and_volatility['Reversion Penalty'] = (
    -2 * np.minimum(
        abs(swings_and_volatility['2012-2016 swing']),
        abs(swings_and_volatility['2016-2020 swing'])
    ) * (swings_and_volatility['2012-2016 swing'] * swings_and_volatility['2016-2020 swing'] < 0)
)

swings_and_volatility['Recency-Weighted Swing'] = (
    swings_and_volatility['2000-2004 absolute swing'] * 0.5 +
    swings_and_volatility['2004-2008 absolute swing'] * 0.75 +
    swings_and_volatility['2008-2012 absolute swing'] * 1.0 +
    swings_and_volatility['2012-2016 absolute swing'] * 1.25 +
    swings_and_volatility['2016-2020 absolute swing'] * 1.5
)

swings_and_volatility['Adjusted volatility score v3B'] = (
    swings_and_volatility['Volatility'] + 
    swings_and_volatility['Recency-Weighted Swing'] + 
    swings_and_volatility['Volatility minus absolute change'] +
    (swings_and_volatility['Volatility div absolute change'] / 100) +
    swings_and_volatility['Average 3P % (± national avg)'] + 
    swings_and_volatility['Max 3P % (± national avg)'] + 
    swings_and_volatility['Min 3P % (± national avg)'] +
    swings_and_volatility['3P% Net Effect of Outliers'] +
    swings_and_volatility['2P Net Effect of Outliers'] -
    swings_and_volatility['Largest minus smallest'] +
    swings_and_volatility['Reversion Penalty']
)

In [66]:
swings_and_volatility.nlargest(10, 'Adjusted volatility score v3B')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,Adjusted volatility score,Adjusted volatility score v2,V1 vs V2,Adjusted volatility score v3,V1 vs V3,V2 vs V3,Reversion Penalty,Adjusted volatility score v3a,Recency-Weighted Swing,Adjusted volatility score v3B
2748,Cache County,Utah,-62.61,-65.71,-45.56,-68.09,-27.25,-36.64,-3.10,3.10,...,240.012784,214.042784,-25.97,176.302784,-63.71,-37.74,-18.78,185.692784,104.3275,252.460284
2768,Tooele County,Utah,-30.50,-48.32,-29.81,-50.59,-30.22,-38.31,-17.82,17.82,...,208.120380,200.310380,-7.81,187.620380,-20.50,-12.69,-16.18,195.710380,81.1700,244.520380
2760,Morgan County,Utah,-60.26,-73.65,-63.01,-80.72,-50.29,-61.99,-13.39,13.39,...,207.788946,206.058946,-1.73,186.268946,-21.52,-19.79,-23.40,197.968946,87.9725,239.141446
1961,Benson County,North Dakota,-4.78,8.64,33.53,17.02,-4.33,-13.87,13.42,13.42,...,190.008439,180.918439,-9.09,165.568439,-24.44,-15.35,-0.00,156.028439,82.8850,238.913439
2650,Maverick County,Texas,30.90,19.17,57.03,58.05,55.80,9.45,-11.73,11.73,...,240.472067,219.022067,-21.45,173.692067,-66.78,-45.33,-0.00,171.442067,107.6175,234.959567
1977,Grant County,North Dakota,-59.00,-55.39,-23.10,-48.90,-66.83,-67.92,3.61,3.61,...,200.172975,191.252975,-8.92,160.052975,-40.12,-31.20,-0.00,158.962975,75.8700,234.832975
2770,Utah County,Utah,-68.03,-74.35,-58.91,-78.60,-36.55,-41.07,-6.32,6.32,...,217.710130,190.750130,-26.96,153.220130,-64.49,-37.53,-9.04,157.740130,93.7725,233.432630
2751,Davis County,Utah,-51.82,-59.76,-42.26,-61.92,-24.16,-27.51,-7.94,7.94,...,211.672944,187.362944,-24.31,152.952944,-58.72,-34.41,-6.70,156.302944,88.9800,231.882944
552,Madison County,Idaho,-79.43,-84.79,-72.79,-87.52,-49.33,-63.66,-5.36,5.36,...,218.919467,203.149467,-15.77,170.319467,-48.60,-32.83,-28.66,184.649467,95.6425,222.971967
2747,Box Elder County,Utah,-62.86,-73.53,-62.53,-77.89,-50.41,-63.19,-10.67,10.67,...,195.787936,195.457936,-0.33,178.647936,-17.14,-16.81,-25.56,191.427936,82.4650,222.772936

In [67]:
# Calculate if swing and reversal occurred
swing_1 = swings_and_volatility['2012-2016 swing']
swing_2 = swings_and_volatility['2016-2020 swing']

# Check for reversal
opposite = (swing_1 * swing_2 < 0)

# How well they cancel each other
magnitude_similarity = 1 - abs(abs(swing_1) - abs(swing_2)) / (abs(swing_1) + abs(swing_2) + 1e-5)

# Apply a sharp penalty for high-cancellation reversals
swings_and_volatility['Isolated Spike Penalty'] = (
    -4 * np.minimum(abs(swing_1), abs(swing_2)) * opposite * magnitude_similarity
)

swings_and_volatility['Adjusted volatility score v3c'] = (
    swings_and_volatility['Volatility'] + 
    swings_and_volatility['Recency-Weighted Swing'] + 
    swings_and_volatility['Volatility minus absolute change'] +
    (swings_and_volatility['Volatility div absolute change'] / 100) +
    swings_and_volatility['Average 3P % (± national avg)'] + 
    swings_and_volatility['Max 3P % (± national avg)'] + 
    swings_and_volatility['Min 3P % (± national avg)'] +
    swings_and_volatility['3P% Net Effect of Outliers'] +
    swings_and_volatility['2P Net Effect of Outliers'] -
    swings_and_volatility['Largest minus smallest'] +
    swings_and_volatility['Isolated Spike Penalty']
)

In [69]:
swings_and_volatility.nlargest(10, 'Adjusted volatility score v3c')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,V1 vs V2,Adjusted volatility score v3,V1 vs V3,V2 vs V3,Reversion Penalty,Adjusted volatility score v3a,Recency-Weighted Swing,Adjusted volatility score v3B,Isolated Spike Penalty,Adjusted volatility score v3c
2748,Cache County,Utah,-62.61,-65.71,-45.56,-68.09,-27.25,-36.64,-3.10,3.10,...,-25.97,176.302784,-63.71,-37.74,-18.78,185.692784,104.3275,252.460284,-14.042943,257.197341
2768,Tooele County,Utah,-30.50,-48.32,-29.81,-50.59,-30.22,-38.31,-17.82,17.82,...,-7.81,187.620380,-20.50,-12.69,-16.18,195.710380,81.1700,244.520380,-18.397222,242.303157
2770,Utah County,Utah,-68.03,-74.35,-58.91,-78.60,-36.55,-41.07,-6.32,6.32,...,-26.96,153.220130,-64.49,-37.53,-9.04,157.740130,93.7725,233.432630,-3.509627,238.963003
1961,Benson County,North Dakota,-4.78,8.64,33.53,17.02,-4.33,-13.87,13.42,13.42,...,-9.09,165.568439,-24.44,-15.35,-0.00,156.028439,82.8850,238.913439,-0.000000,238.913439
2760,Morgan County,Utah,-60.26,-73.65,-63.01,-80.72,-50.29,-61.99,-13.39,13.39,...,-1.73,186.268946,-21.52,-19.79,-23.40,197.968946,87.9725,239.141446,-25.993834,236.547612
2751,Davis County,Utah,-51.82,-59.76,-42.26,-61.92,-24.16,-27.51,-7.94,7.94,...,-24.31,152.952944,-58.72,-34.41,-6.70,156.302944,88.9800,231.882944,-2.183900,236.399045
2650,Maverick County,Texas,30.90,19.17,57.03,58.05,55.80,9.45,-11.73,11.73,...,-21.45,173.692067,-66.78,-45.33,-0.00,171.442067,107.6175,234.959567,-0.000000,234.959567
1977,Grant County,North Dakota,-59.00,-55.39,-23.10,-48.90,-66.83,-67.92,3.61,3.61,...,-8.92,160.052975,-40.12,-31.20,-0.00,158.962975,75.8700,234.832975,-0.000000,234.832975
552,Madison County,Idaho,-79.43,-84.79,-72.79,-87.52,-49.33,-63.66,-5.36,5.36,...,-15.77,170.319467,-48.60,-32.83,-28.66,184.649467,95.6425,222.971967,-31.279350,220.352617
2705,Starr County,Texas,54.27,47.51,69.26,73.32,60.18,5.00,-6.76,6.76,...,-49.27,150.726292,-100.39,-51.12,-0.00,137.586292,122.9475,218.493792,-0.000000,218.493792

Something like this feels right. Many of these Utah counties did not sustain their 2016 shift, but in 2020 still ended up noticeably more competitive than pre-2016.
BUT - The swing reversal metric should be more robust to any year. While still keeping the recency bonus.

In [70]:
swings_and_volatility.nsmallest(10, 'Adjusted volatility score v3c')

,County,State,2000 D-R margin,2004 D-R margin,2008 D-R margin,2012 D-R margin,2016 D-R margin,2020 D-R margin,2000-2004 swing,2000-2004 absolute swing,...,V1 vs V2,Adjusted volatility score v3,V1 vs V3,V2 vs V3,Reversion Penalty,Adjusted volatility score v3a,Recency-Weighted Swing,Adjusted volatility score v3B,Isolated Spike Penalty,Adjusted volatility score v3c
1377,Carroll County,Mississippi,-29.23,-31.47,-31.31,-32.60,-38.33,-38.50,-2.24,2.24,...,-9.27,-2.552173,-14.84,-5.57,-0.00,-2.722173,9.9475,7.225327,-0.000000,7.225327
2614,Jefferson County,Texas,5.86,2.87,2.25,1.61,-0.48,-1.58,-2.99,2.99,...,-7.44,1.560815,-9.81,-2.37,-0.00,0.460815,6.8625,7.323315,-0.000000,7.323315
2103,Beaver County,Oklahoma,-71.38,-76.88,-78.50,-78.84,-81.00,-81.64,-5.50,5.50,...,-10.26,1.092482,-15.42,-5.16,-0.00,0.452482,7.9650,8.417482,-0.000000,8.417482
1393,Harrison County,Mississippi,-24.92,-26.25,-26.07,-25.82,-30.30,-25.20,-1.33,1.33,...,-0.28,18.910815,-5.20,-4.92,-8.96,23.390815,14.3000,19.150815,-16.760252,11.350563
951,Stevens County,Kansas,-64.85,-71.78,-72.02,-73.60,-72.93,-74.99,-6.93,6.93,...,-10.14,5.980470,-16.83,-6.69,-1.34,6.650470,9.1525,11.732970,-1.315463,11.757507
1121,Rapides Parish,Louisiana,-20.26,-28.83,-28.66,-29.55,-32.54,-32.06,-8.57,8.57,...,-11.80,3.793583,-20.20,-8.40,-0.96,4.273583,9.7600,12.113583,-0.531186,12.542398
325,Leon County,Florida,21.69,23.65,24.26,23.64,25.14,28.28,1.96,1.96,...,-6.59,7.346030,-9.12,-2.53,-0.00,5.846030,8.6425,12.848530,-0.000000,12.848530
2670,Ochiltree County,Texas,-82.25,-84.07,-83.88,-82.40,-78.41,-79.53,-1.82,1.82,...,-2.72,7.590766,-6.52,-3.80,-2.24,8.710766,9.2000,13.430766,-1.963841,13.706925
2136,Kingfisher County,Oklahoma,-55.96,-69.28,-68.38,-68.86,-71.28,-72.19,-13.32,13.32,...,-16.23,3.066924,-29.07,-12.84,-0.00,2.156924,12.2050,14.361924,-0.000000,14.361924
958,Wichita County,Kansas,-59.82,-64.60,-66.43,-67.27,-65.80,-68.08,-4.78,4.78,...,-8.26,11.439374,-12.20,-3.94,-2.94,12.909374,9.8600,16.079374,-4.609923,14.409451

In [71]:
swings_and_volatility.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3111 entries, 0 to 3110
Data columns (total 57 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   County                               3111 non-null   object
 1   State                                3111 non-null   object
 2   2000 D-R margin                      3111 non-null   float64
 3   2004 D-R margin                      3111 non-null   float64
 4   2008 D-R margin                      3111 non-null   float64
 5   2012 D-R margin                      3111 non-null   float64
 6   2016 D-R margin                      3111 non-null   float64
 7   2020 D-R margin                      3111 non-null   float64
 8   2000-2004 swing                      3111 non-null   float64
 9   2000-2004 absolute swing             3111 non-null   float64
 10  2004-2008 swing                      3111 non-null   float64
 11  2004-2008 absolute swing             3111 non-null   float64
 12  2008-2012 swing                      3111 non-null   float64
 13  2008-2012 absolute swing             3111 non-null   float64
 14  2012-2016 swing                      3111 non-null   float64
 15  2012-2016 absolute swing             3111 non-null   float64
 16  2016-2020 swing                      3111 non-null   float64
 17  2016-2020 absolute swing             3111 non-null   float64
 18  2000-2020 net swing                  3111 non-null   float64
 19  2000-2020 absolute net swing         3111 non-null   float64
 20  Volatility                           3111 non-null   float64
 21  Volatility minus absolute change     3111 non-null   float64
 22  Volatility div absolute change       3111 non-null   float64
 23  Average Other %                      3111 non-null   float64
 24  Largest Other %                      3111 non-null   float64
 25  Smallest Other %                     3111 non-null   float64
 26  Year of Largest Other %              3111 non-null   int64
 27  Year of Smallest Other %             3111 non-null   int64
 28  Average 3P % Excl. Largest Outlier   3111 non-null   float64
 29  Average 3P % Excl. Smallest Outlier  3111 non-null   float64
 30  3P% Effect of Largest Outlier        3111 non-null   float64
 31  3P% Effect of Smallest Outlier       3111 non-null   float64
 32  3P% Net Effect of Outliers           3111 non-null   float64
 33  Average 3P % (± national avg)        3111 non-null   float64
 34  Max 3P % (± national avg)            3111 non-null   float64
 35  Min 3P % (± national avg)            3111 non-null   float64
 36  Average Absolute Swing               3111 non-null   float64
 37  Largest Absolute Swing               3111 non-null   float64
 38  Smallest Absolute Swing              3111 non-null   float64
 39  Largest minus smallest               3111 non-null   float64
 40  Largest ± average                    3111 non-null   float64
 41  Smallest ± average                   3111 non-null   float64
 42  Average 2P Excl. Largest Outlier     3111 non-null   float64
 43  Average 2P Excl. Smallest Outlier    3111 non-null   float64
 44  2P Net Effect of Outliers            3111 non-null   float64
 45  Adjusted volatility score            3111 non-null   float64
 46  Adjusted volatility score v2         3111 non-null   float64
 47  V1 vs V2                             3111 non-null   float64
 48  Adjusted volatility score v3         3111 non-null   float64
 49  V1 vs V3                             3111 non-null   float64
 50  V2 vs V3                             3111 non-null   float64
 51  Reversion Penalty                    3111 non-null   float64
 52  Adjusted volatility score v3a        3111 non-null   float64
 53  Recency-Weighted Swing               3111 non-null   float64
 54  Adjusted volatility score v3B        3111 non-null   float64
 55  Isolated Spike Penalty               3111 non-null   float64
 56  Adjusted volatility score v3c        3111 non-null   float64
dtypes: float64(53), int64(2), object(2)
memory usage: 1.4+ MB

# Old 2PA Absolute Error calculation
Logic extended to other categories

In [ ]:
# Step 1: Compute the national average of Absolute Error (2PA)
national_avg_error = rfr_2pas['Absolute Error (2PA)'].mean()

# Step 2: Define function to compute all stats
def summarize_with_offsets(group):
    errors = group['Absolute Error (2PA)'].values
    years = group['Year'].values
    
    largest_idx = np.argmax(errors)
    smallest_idx = np.argmin(errors)
    
    largest = errors[largest_idx]
    smallest = errors[smallest_idx]
    mean = errors.mean()
    
    # Exclude extremes
    errors_excl_largest = np.delete(errors, largest_idx)
    errors_excl_smallest = np.delete(errors, smallest_idx)
    mean_excl_largest = errors_excl_largest.mean() if len(errors_excl_largest) > 0 else np.nan
    mean_excl_smallest = errors_excl_smallest.mean() if len(errors_excl_smallest) > 0 else np.nan

    return pd.Series({
        'Absolute Error (2PA) County Avg': mean,
        'Absolute Error (2PA) Largest': errors[largest_idx],
        'Absolute Error (2PA) Largest ± County Avg': largest - mean,
        'Absolute Error (2PA) Year of Largest': years[largest_idx],
        'Absolute Error (2PA) Smallest': errors[smallest_idx],
        'Absolute Error (2PA) Smallest ± County Avg': smallest - mean,
        'Absolute Error (2PA) Year of Smallest': years[smallest_idx],
        'Absolute Error (2PA) Average ± Natl. Avg': mean - national_avg_error,
        'Absolute Error (2PA) Largest ± Natl. Avg': largest - national_avg_error,
        'Absolute Error (2PA) Smallest ± Natl. Avg': smallest - national_avg_error,
        'Absolute Error (2PA) Avg. Excl. Largest Outlier': mean_excl_largest,
        'Absolute Error (2PA) Avg. Excl. Smallest Outlier': mean_excl_smallest,
        'Absolute Error (2PA) Effect of Largest Error': abs(mean - mean_excl_largest),
        'Absolute Error (2PA) Effect of Smallest Error': abs(mean - mean_excl_smallest),
        'Absolute Error (2PA) Total Effect of Extremes': abs(mean - mean_excl_largest) + abs(mean - mean_excl_smallest)
    })


# Apply function to grouped DataFrame
summary_df = rfr_2pas.groupby(['State', 'County']).apply(summarize_with_offsets).reset_index()

# Set columns to integer
summary_df['Absolute Error (2PA) Year of Largest'] = summary_df['Absolute Error (2PA) Year of Largest'].astype(int)
summary_df['Absolute Error (2PA) Year of Smallest'] = summary_df['Absolute Error (2PA) Year of Smallest'].astype(int)