In [2]:
import pandas as pd
import numpy as np

# Load election dataset.

In [3]:
election_pivot = pd.read_csv("/Users/matthewcavanaugh/Desktop/GitHub/us-presidential-elections-by-county/sources/Election CLEANED.csv", dtype={'FIPS Code': str})
election_pivot

,Year,State,County,FIPS Code,Democrat Votes,Democrat Percentage,Republican Votes,Republican Percentage,Other Votes,Other Percentage,Total Votes,D-R margin,Two party vote share
0,2000,Alabama,Autauga County,01001,4942,28.72,11993,69.69,273,1.59,17208,-40.97,98.41
1,2000,Alabama,Baldwin County,01003,13997,24.78,40872,72.37,1611,2.85,56480,-47.59,97.15
2,2000,Alabama,Barbour County,01005,5188,49.91,5096,49.02,111,1.07,10395,0.89,98.93
3,2000,Alabama,Bibb County,01007,2710,38.16,4273,60.17,118,1.66,7101,-22.01,98.33
4,2000,Alabama,Blount County,01009,4977,27.69,12667,70.48,329,1.83,17973,-42.79,98.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18661,2020,Wyoming,Sweetwater County,56037,3823,22.89,12229,73.24,646,3.87,16698,-50.35,96.13
18662,2020,Wyoming,Teton County,56039,9848,66.60,4341,29.36,598,4.04,14787,37.24,95.96
18663,2020,Wyoming,Uinta County,56041,1591,16.82,7496,79.25,372,3.93,9459,-62.43,96.07
18664,2020,Wyoming,Washakie County,56043,651,16.15,3245,80.48,136,3.37,4032,-64.33,96.63
18665,2020,Wyoming,Weston County,56045,360,10.11,3107,87.28,93,2.61,3560,-77.17,97.39

# COMBINING WITH UNEMPLOYMENT

In [4]:
election_pivot

,Year,State,County,FIPS Code,Democrat Votes,Democrat Percentage,Republican Votes,Republican Percentage,Other Votes,Other Percentage,Total Votes,D-R margin,Two party vote share
0,2000,Alabama,Autauga County,01001,4942,28.72,11993,69.69,273,1.59,17208,-40.97,98.41
1,2000,Alabama,Baldwin County,01003,13997,24.78,40872,72.37,1611,2.85,56480,-47.59,97.15
2,2000,Alabama,Barbour County,01005,5188,49.91,5096,49.02,111,1.07,10395,0.89,98.93
3,2000,Alabama,Bibb County,01007,2710,38.16,4273,60.17,118,1.66,7101,-22.01,98.33
4,2000,Alabama,Blount County,01009,4977,27.69,12667,70.48,329,1.83,17973,-42.79,98.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18661,2020,Wyoming,Sweetwater County,56037,3823,22.89,12229,73.24,646,3.87,16698,-50.35,96.13
18662,2020,Wyoming,Teton County,56039,9848,66.60,4341,29.36,598,4.04,14787,37.24,95.96
18663,2020,Wyoming,Uinta County,56041,1591,16.82,7496,79.25,372,3.93,9459,-62.43,96.07
18664,2020,Wyoming,Washakie County,56043,651,16.15,3245,80.48,136,3.37,4032,-64.33,96.63
18665,2020,Wyoming,Weston County,56045,360,10.11,3107,87.28,93,2.61,3560,-77.17,97.39

Unemployment

In [5]:
unemployment = pd.read_csv("/Users/matthewcavanaugh/Desktop/GitHub/us-presidential-elections-by-county/sources/Unemployment CLEANED.csv")
unemployment

       FIPS Code    State          County  Unemployment rate  Year
0           1001  Alabama  Autauga County                4.1  2000
1           1001  Alabama  Autauga County                4.7  2004
2           1001  Alabama  Autauga County                5.3  2008
3           1001  Alabama  Autauga County                7.1  2012
4           1001  Alabama  Autauga County                5.1  2016
...          ...      ...             ...                ...   ...
18673      56045  Wyoming   Weston County                4.0  2004
18674      56045  Wyoming   Weston County                3.1  2008
18675      56045  Wyoming   Weston County                4.2  2012
18676      56045  Wyoming   Weston County                5.0  2016
18677      56045  Wyoming   Weston County                3.9  2020

[18678 rows x 5 columns]

Matching differently formatted County names on FIPS

In [6]:
# Step 1: Create lookup from election_pivot: FIPS -> County
fips_to_county = election_pivot[['FIPS Code', 'County']].drop_duplicates().set_index('FIPS Code')['County']

# Step 2: Identify conflicting rows
conflict_mask = (
    unemployment['FIPS Code'].isin(fips_to_county.index) &
    (unemployment['County'] != unemployment['FIPS Code'].map(fips_to_county))
)

# Step 3: Apply correction — use election_pivot county name where FIPS matches but name differs
unemployment.loc[conflict_mask, 'County'] = unemployment.loc[conflict_mask, 'FIPS Code'].map(fips_to_county)

In [7]:
unemployment

       FIPS Code    State          County  Unemployment rate  Year
0           1001  Alabama  Autauga County                4.1  2000
1           1001  Alabama  Autauga County                4.7  2004
2           1001  Alabama  Autauga County                5.3  2008
3           1001  Alabama  Autauga County                7.1  2012
4           1001  Alabama  Autauga County                5.1  2016
...          ...      ...             ...                ...   ...
18673      56045  Wyoming   Weston County                4.0  2004
18674      56045  Wyoming   Weston County                3.1  2008
18675      56045  Wyoming   Weston County                4.2  2012
18676      56045  Wyoming   Weston County                5.0  2016
18677      56045  Wyoming   Weston County                3.9  2020

[18678 rows x 5 columns]

In [8]:
election_pivot

,Year,State,County,FIPS Code,Democrat Votes,Democrat Percentage,Republican Votes,Republican Percentage,Other Votes,Other Percentage,Total Votes,D-R margin,Two party vote share
0,2000,Alabama,Autauga County,01001,4942,28.72,11993,69.69,273,1.59,17208,-40.97,98.41
1,2000,Alabama,Baldwin County,01003,13997,24.78,40872,72.37,1611,2.85,56480,-47.59,97.15
2,2000,Alabama,Barbour County,01005,5188,49.91,5096,49.02,111,1.07,10395,0.89,98.93
3,2000,Alabama,Bibb County,01007,2710,38.16,4273,60.17,118,1.66,7101,-22.01,98.33
4,2000,Alabama,Blount County,01009,4977,27.69,12667,70.48,329,1.83,17973,-42.79,98.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18661,2020,Wyoming,Sweetwater County,56037,3823,22.89,12229,73.24,646,3.87,16698,-50.35,96.13
18662,2020,Wyoming,Teton County,56039,9848,66.60,4341,29.36,598,4.04,14787,37.24,95.96
18663,2020,Wyoming,Uinta County,56041,1591,16.82,7496,79.25,372,3.93,9459,-62.43,96.07
18664,2020,Wyoming,Washakie County,56043,651,16.15,3245,80.48,136,3.37,4032,-64.33,96.63
18665,2020,Wyoming,Weston County,56045,360,10.11,3107,87.28,93,2.61,3560,-77.17,97.39

We'll have to drop Broomfield from unemployment as well, and fix spelling for DC.

In [9]:
unemployment = unemployment[~unemployment['County'].str.contains("Broomfield County", na=False)]
unemployment = unemployment.replace({"District of Columbia": "District Of Columbia"})

In [10]:
# Ensure both are strings and zero-padded to 5 digits
election_pivot['FIPS Code'] = election_pivot['FIPS Code'].astype(str).str.zfill(5)
unemployment['FIPS Code'] = unemployment['FIPS Code'].astype(str).str.zfill(5)

# Ensure Year is integer
unemployment['Year'] = unemployment['Year'].astype(int)
election_pivot['Year'] = election_pivot['Year'].astype(int)

In [11]:
election_pivot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18666 entries, 0 to 18665
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   18666 non-null  int64
 1   State                  18666 non-null  object
 2   County                 18666 non-null  object
 3   FIPS Code              18666 non-null  object
 4   Democrat Votes         18666 non-null  int64
 5   Democrat Percentage    18666 non-null  float64
 6   Republican Votes       18666 non-null  int64
 7   Republican Percentage  18666 non-null  float64
 8   Other Votes            18666 non-null  int64
 9   Other Percentage       18666 non-null  float64
 10  Total Votes            18666 non-null  int64
 11  D-R margin             18666 non-null  float64
 12  Two party vote share   18666 non-null  float64
dtypes: float64(5), int64(5), object(3)
memory usage: 1.9+ MB

In [12]:
unemployment.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18672 entries, 0 to 18677
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   FIPS Code          18672 non-null  object
 1   State              18672 non-null  object
 2   County             18672 non-null  object
 3   Unemployment rate  18672 non-null  float64
 4   Year               18672 non-null  int64
dtypes: float64(1), int64(1), object(3)
memory usage: 875.2+ KB

In [13]:
unemployment = unemployment[~unemployment['County'].str.contains("Broomfield County/City", na=False)]

In [14]:
unemployment.loc[
    unemployment['State'] == 'District of Columbia',
    'State'
] = 'District Of Columbia'

In [15]:
# Get unique combinations from each dataframe
unemp_keys = unemployment[['State', 'County', 'Year']].drop_duplicates()
election_keys = election_pivot[['State', 'County', 'Year']].drop_duplicates()

# Find mismatches
unemp_not_in_elec = pd.merge(unemp_keys, election_keys, 
                             on=['State', 'County', 'Year'], 
                             how='left', indicator=True)
unemp_not_in_elec = unemp_not_in_elec[unemp_not_in_elec['_merge'] == 'left_only']
unemp_not_in_elec = unemp_not_in_elec.drop(columns=['_merge'])

elec_not_in_unemp = pd.merge(election_keys, unemp_keys, 
                             on=['State', 'County', 'Year'], 
                             how='left', indicator=True)
elec_not_in_unemp = elec_not_in_unemp[elec_not_in_unemp['_merge'] == 'left_only']
elec_not_in_unemp = elec_not_in_unemp.drop(columns=['_merge'])

# Display the results
print("In unemployment but not in election_pivot:")
print(unemp_not_in_elec)

print("\nIn election_pivot but not in unemployment:")
print(elec_not_in_unemp)

In unemployment but not in election_pivot:
          State            County  Year
6666  Louisiana    Lasalle Parish  2000
6667  Louisiana    Lasalle Parish  2004
6668  Louisiana    Lasalle Parish  2008
6669  Louisiana    Lasalle Parish  2012
6670  Louisiana    Lasalle Parish  2016
6671  Louisiana    Lasalle Parish  2020
8106  Minnesota  St. Louis County  2000
8107  Minnesota  St. Louis County  2004
8108  Minnesota  St. Louis County  2008
8109  Minnesota  St. Louis County  2012
8110  Minnesota  St. Louis County  2016
8111  Minnesota  St. Louis County  2020

In election_pivot but not in unemployment:
           State              County  Year
1109   Louisiana     La Salle Parish  2000
1351   Minnesota  Saint Louis County  2000
4220   Louisiana     La Salle Parish  2004
4462   Minnesota  Saint Louis County  2004
7331   Louisiana     La Salle Parish  2008
7573   Minnesota  Saint Louis County  2008
10442  Louisiana     La Salle Parish  2012
10684  Minnesota  Saint Louis County  2012
13553  Louisiana     La Salle Parish  2016
13795  Minnesota  Saint Louis County  2016
16664  Louisiana     La Salle Parish  2020
16906  Minnesota  Saint Louis County  2020

In [16]:
# Define a mapping of old county names to preferred names for unemployment
county_name_corrections = {
    'La Salle Parish': 'Lasalle Parish',
    'Saint Louis County': 'St. Louis County',
    'Doña Ana County': 'Dona Ana County'
}

# Apply corrections
unemployment['County'] = unemployment['County'].replace(county_name_corrections)
election_pivot['County'] = election_pivot['County'].replace(county_name_corrections)

In [17]:
unemployment_nulls = election_pivot[election_pivot.isnull().any(axis=1)]
unemployment_nulls

Empty DataFrame
Columns: [Year, State, County, FIPS Code, Democrat Votes, Democrat Percentage, Republican Votes, Republican Percentage, Other Votes, Other Percentage, Total Votes, D-R margin, Two party vote share]
Index: []

In [18]:
unemployment['FIPS Code'].nunique()

3112

In [19]:
election_pivot['FIPS Code'].value_counts()

FIPS Code
01001    6
39157    6
39113    6
39115    6
39117    6
        ..
21145    6
21147    6
21149    6
21163    6
56045    6
Name: count, Length: 3111, dtype: int64

In [20]:
def clean_fips(fips):
    # Convert to string, remove decimal if any, then pad with leading zeros to length 5
    fips_str = str(fips).split('.')[0]
    return fips_str.zfill(5)

# Apply to both dataframes
election_pivot['FIPS Code'] = election_pivot['FIPS Code'].apply(clean_fips)
unemployment['FIPS Code'] = unemployment['FIPS Code'].apply(clean_fips)

In [21]:
election_pivot['FIPS Code'].nunique()

3111

In [22]:
unemployment['FIPS Code'].nunique()

3112

In [23]:
set_unemp = set(unemployment['FIPS Code'].unique())
set_elect = set(election_pivot['FIPS Code'].unique())

missing_in_election = set_unemp - set_elect
missing_in_unemployment = set_elect - set_unemp

print("In unemployment but not in election:", missing_in_election)
print("In election but not in unemployment:", missing_in_unemployment)

In unemployment but not in election: {'11000'}
In election but not in unemployment: set()

In [24]:
unemployment[unemployment['FIPS Code'] == '11000']

,FIPS Code,State,County,Unemployment rate,Year
1740,11000,District Of Columbia,District Of Columbia,5.7,2000
1741,11000,District Of Columbia,District Of Columbia,8.1,2004
1742,11000,District Of Columbia,District Of Columbia,6.8,2008
1743,11000,District Of Columbia,District Of Columbia,9.0,2012
1744,11000,District Of Columbia,District Of Columbia,6.2,2016
1745,11000,District Of Columbia,District Of Columbia,7.9,2020

In [25]:
election_pivot[election_pivot['State'].str.contains('District')]

,Year,State,County,FIPS Code,Democrat Votes,Democrat Percentage,Republican Votes,Republican Percentage,Other Votes,Other Percentage,Total Votes,D-R margin,Two party vote share
289,2000,District Of Columbia,District Of Columbia,11001,171923,85.16,18073,8.95,11898,5.89,201894,76.21,94.11
3400,2004,District Of Columbia,District Of Columbia,11001,202970,89.18,21256,9.34,3360,1.48,227586,79.84,98.52
6511,2008,District Of Columbia,District Of Columbia,11001,245800,92.46,17367,6.53,2686,1.01,265853,85.93,98.99
9622,2012,District Of Columbia,District Of Columbia,11001,267070,90.91,21381,7.28,5313,1.81,293764,83.63,98.19
12733,2016,District Of Columbia,District Of Columbia,11001,282830,90.86,12723,4.09,15715,5.05,311268,86.77,94.95
15844,2020,District Of Columbia,District Of Columbia,11001,317323,92.15,18586,5.40,8447,2.45,344356,86.75,97.55

In [26]:
unemployment.loc[unemployment['FIPS Code'] == '11000', 'FIPS Code'] = '11001'

In [27]:
unemployment['Year'].value_counts()

Year
2000    3112
2004    3112
2008    3112
2012    3112
2016    3112
2020    3112
Name: count, dtype: int64

In [28]:
election_pivot['Year'].value_counts()

Year
2000    3111
2004    3111
2008    3111
2012    3111
2016    3111
2020    3111
Name: count, dtype: int64

In [29]:
dupes = unemployment[unemployment.duplicated(subset=['Year', 'State', 'County', 'FIPS Code'], keep=False)]

print(f"Number of duplicate rows based on Year, State, County, FIPS Code: {len(dupes)}")
print(dupes.sort_values(['Year', 'State', 'County']).head(10))

Number of duplicate rows based on Year, State, County, FIPS Code: 12
     FIPS Code                 State                County  Unemployment rate  \
1740     11001  District Of Columbia  District Of Columbia                5.7
1746     11001  District Of Columbia  District Of Columbia                5.7
1741     11001  District Of Columbia  District Of Columbia                8.1
1747     11001  District Of Columbia  District Of Columbia                8.1
1742     11001  District Of Columbia  District Of Columbia                6.8
1748     11001  District Of Columbia  District Of Columbia                6.8
1743     11001  District Of Columbia  District Of Columbia                9.0
1749     11001  District Of Columbia  District Of Columbia                9.0
1744     11001  District Of Columbia  District Of Columbia                6.2
1750     11001  District Of Columbia  District Of Columbia                6.2

      Year
1740  2000
1746  2000
1741  2004
1747  2004
1742  2008
1748  2008
1743  2012
1749  2012
1744  2016
1750  2016

In [30]:
unemployment = unemployment.drop_duplicates(subset=['Year', 'State', 'County', 'FIPS Code', 'Unemployment rate'])

In [31]:
dupes = unemployment[unemployment.duplicated(subset=['Year', 'State', 'County', 'FIPS Code'], keep=False)]

print(f"Number of duplicate rows based on Year, State, County, FIPS Code: {len(dupes)}")
print(dupes.sort_values(['Year', 'State', 'County']).head(10))

Number of duplicate rows based on Year, State, County, FIPS Code: 0
Empty DataFrame
Columns: [FIPS Code, State, County, Unemployment rate, Year]
Index: []

In [32]:
unemployment.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18666 entries, 0 to 18677
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   FIPS Code          18666 non-null  object
 1   State              18666 non-null  object
 2   County             18666 non-null  object
 3   Unemployment rate  18666 non-null  float64
 4   Year               18666 non-null  int64
dtypes: float64(1), int64(1), object(3)
memory usage: 875.0+ KB

In [33]:
election_pivot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18666 entries, 0 to 18665
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   18666 non-null  int64
 1   State                  18666 non-null  object
 2   County                 18666 non-null  object
 3   FIPS Code              18666 non-null  object
 4   Democrat Votes         18666 non-null  int64
 5   Democrat Percentage    18666 non-null  float64
 6   Republican Votes       18666 non-null  int64
 7   Republican Percentage  18666 non-null  float64
 8   Other Votes            18666 non-null  int64
 9   Other Percentage       18666 non-null  float64
 10  Total Votes            18666 non-null  int64
 11  D-R margin             18666 non-null  float64
 12  Two party vote share   18666 non-null  float64
dtypes: float64(5), int64(5), object(3)
memory usage: 1.9+ MB

In [34]:
election_pivot = pd.merge(
    election_pivot,
    unemployment[['Year', 'State', 'County', 'FIPS Code', 'Unemployment rate']],
    on=['Year', 'State', 'County', 'FIPS Code'],
    how='left'
)

In [35]:
election_pivot

,Year,State,County,FIPS Code,Democrat Votes,Democrat Percentage,Republican Votes,Republican Percentage,Other Votes,Other Percentage,Total Votes,D-R margin,Two party vote share,Unemployment rate
0,2000,Alabama,Autauga County,01001,4942,28.72,11993,69.69,273,1.59,17208,-40.97,98.41,4.1
1,2000,Alabama,Baldwin County,01003,13997,24.78,40872,72.37,1611,2.85,56480,-47.59,97.15,3.7
2,2000,Alabama,Barbour County,01005,5188,49.91,5096,49.02,111,1.07,10395,0.89,98.93,5.6
3,2000,Alabama,Bibb County,01007,2710,38.16,4273,60.17,118,1.66,7101,-22.01,98.33,5.4
4,2000,Alabama,Blount County,01009,4977,27.69,12667,70.48,329,1.83,17973,-42.79,98.17,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18661,2020,Wyoming,Sweetwater County,56037,3823,22.89,12229,73.24,646,3.87,16698,-50.35,96.13,7.5
18662,2020,Wyoming,Teton County,56039,9848,66.60,4341,29.36,598,4.04,14787,37.24,95.96,5.9
18663,2020,Wyoming,Uinta County,56041,1591,16.82,7496,79.25,372,3.93,9459,-62.43,96.07,6.4
18664,2020,Wyoming,Washakie County,56043,651,16.15,3245,80.48,136,3.37,4032,-64.33,96.63,5.3
18665,2020,Wyoming,Weston County,56045,360,10.11,3107,87.28,93,2.61,3560,-77.17,97.39,3.9

In [36]:
election_pivot['FIPS Code'].nunique()

3111

In [37]:
election_pivot.isnull().sum()

Year                     0
State                    0
County                   0
FIPS Code                0
Democrat Votes           0
Democrat Percentage      0
Republican Votes         0
Republican Percentage    0
Other Votes              0
Other Percentage         0
Total Votes              0
D-R margin               0
Two party vote share     0
Unemployment rate        0
dtype: int64

# COMBINING WITH EDUCATION

In [38]:
education = pd.read_csv("/Users/matthewcavanaugh/Desktop/GitHub/us-presidential-elections-by-county/sources/Education CLEANED.csv")

In [39]:
education = education.sort_values(by=['Year', 'State', 'County', 'FIPS Code'])
education.reset_index(inplace=True)
education.drop('index', axis=1, inplace=True)
education

,Year,State,County,FIPS Code,At least some college,Bachelor's degree or higher,High school graduate,Less than high school
0,2000,Alabama,Autauga County,1001,44.900000,18.000000,78.700000,21.300000
1,2000,Alabama,Baldwin County,1003,52.400000,23.100000,82.000000,18.000000
2,2000,Alabama,Barbour County,1005,32.200000,10.900000,64.600000,35.300000
3,2000,Alabama,Bibb County,1007,27.500000,7.100000,63.200000,36.800000
4,2000,Alabama,Blount County,1009,34.400000,9.600000,70.400000,29.600000
...,...,...,...,...,...,...,...,...
18691,2020,Wyoming,Sweetwater County,56037,60.738243,20.069467,92.326898,7.673102
18692,2020,Wyoming,Teton County,56039,80.223940,60.108324,97.060793,2.939207
18693,2020,Wyoming,Uinta County,56041,58.134929,21.042262,94.030149,5.969851
18694,2020,Wyoming,Washakie County,56043,60.902534,22.151219,91.362635,8.637365
18695,2020,Wyoming,Weston County,56045,54.964355,17.993430,91.561893,8.438107

In [40]:
education['FIPS Code'] = education['FIPS Code'].astype(str).str.zfill(5)
education

,Year,State,County,FIPS Code,At least some college,Bachelor's degree or higher,High school graduate,Less than high school
0,2000,Alabama,Autauga County,01001,44.900000,18.000000,78.700000,21.300000
1,2000,Alabama,Baldwin County,01003,52.400000,23.100000,82.000000,18.000000
2,2000,Alabama,Barbour County,01005,32.200000,10.900000,64.600000,35.300000
3,2000,Alabama,Bibb County,01007,27.500000,7.100000,63.200000,36.800000
4,2000,Alabama,Blount County,01009,34.400000,9.600000,70.400000,29.600000
...,...,...,...,...,...,...,...,...
18691,2020,Wyoming,Sweetwater County,56037,60.738243,20.069467,92.326898,7.673102
18692,2020,Wyoming,Teton County,56039,80.223940,60.108324,97.060793,2.939207
18693,2020,Wyoming,Uinta County,56041,58.134929,21.042262,94.030149,5.969851
18694,2020,Wyoming,Washakie County,56043,60.902534,22.151219,91.362635,8.637365
18695,2020,Wyoming,Weston County,56045,54.964355,17.993430,91.561893,8.438107

In [41]:
# Step 1: Create lookup from election_pivot: FIPS -> County
fips_to_county = election_pivot[['FIPS Code', 'County']].drop_duplicates().set_index('FIPS Code')['County']

# Step 2: Identify conflicting rows
conflict_mask = (
    education['FIPS Code'].isin(fips_to_county.index) &
    (education['County'] != education['FIPS Code'].map(fips_to_county))
)

# Step 3: Apply correction — use election_pivot county name where FIPS matches but name differs
education.loc[conflict_mask, 'County'] = education.loc[conflict_mask, 'FIPS Code'].map(fips_to_county)

In [42]:
education

,Year,State,County,FIPS Code,At least some college,Bachelor's degree or higher,High school graduate,Less than high school
0,2000,Alabama,Autauga County,01001,44.900000,18.000000,78.700000,21.300000
1,2000,Alabama,Baldwin County,01003,52.400000,23.100000,82.000000,18.000000
2,2000,Alabama,Barbour County,01005,32.200000,10.900000,64.600000,35.300000
3,2000,Alabama,Bibb County,01007,27.500000,7.100000,63.200000,36.800000
4,2000,Alabama,Blount County,01009,34.400000,9.600000,70.400000,29.600000
...,...,...,...,...,...,...,...,...
18691,2020,Wyoming,Sweetwater County,56037,60.738243,20.069467,92.326898,7.673102
18692,2020,Wyoming,Teton County,56039,80.223940,60.108324,97.060793,2.939207
18693,2020,Wyoming,Uinta County,56041,58.134929,21.042262,94.030149,5.969851
18694,2020,Wyoming,Washakie County,56043,60.902534,22.151219,91.362635,8.637365
18695,2020,Wyoming,Weston County,56045,54.964355,17.993430,91.561893,8.438107

In [43]:
education.groupby('Year')[['State', 'County', 'FIPS Code']].nunique()

      State  County  FIPS Code
Year
2000     50    1851       3116
2004     50    1851       3116
2008     50    1851       3116
2012     50    1851       3116
2016     50    1851       3116
2020     50    1851       3116

In [44]:
# Define the key columns to compare
key_cols = ['Year', 'State', 'County', 'FIPS Code']

# Find rows in education that are not in election_pivot
education_not_in_election = education.merge(
    election_pivot[key_cols].drop_duplicates(),
    on=key_cols,
    how='left',
    indicator=True
).query('_merge == "left_only"').drop(columns=['_merge'])

# Show the unique counties that are missing
missing_counties = education_not_in_election[['Year', 'State', 'County', 'FIPS Code']].drop_duplicates()

print(missing_counties.sort_values(by=['Year', 'State', 'County']))

       Year                 State                County FIPS Code
222    2000              Colorado     Broomfield County     08014
291    2000  District of Columbia  District Of Columbia     11001
290    2000  District of Columbia  District of Columbia     11000
520    2000                Hawaii        Kalawao County     15005
2803   2000              Virginia          Bedford city     51515
2820   2000              Virginia    Clifton Forge city     51560
3338   2004              Colorado     Broomfield County     08014
3407   2004  District of Columbia  District Of Columbia     11001
3406   2004  District of Columbia  District of Columbia     11000
3636   2004                Hawaii        Kalawao County     15005
5919   2004              Virginia          Bedford city     51515
5936   2004              Virginia    Clifton Forge city     51560
6454   2008              Colorado     Broomfield County     08014
6523   2008  District of Columbia  District Of Columbia     11001
6522   2008  District of Columbia  District of Columbia     11000
6752   2008                Hawaii        Kalawao County     15005
9035   2008              Virginia          Bedford city     51515
9052   2008              Virginia    Clifton Forge city     51560
9570   2012              Colorado     Broomfield County     08014
9639   2012  District of Columbia  District Of Columbia     11001
9638   2012  District of Columbia  District of Columbia     11000
9868   2012                Hawaii        Kalawao County     15005
12151  2012              Virginia          Bedford city     51515
12168  2012              Virginia    Clifton Forge city     51560
12686  2016              Colorado     Broomfield County     08014
12755  2016  District of Columbia  District Of Columbia     11001
12754  2016  District of Columbia  District of Columbia     11000
12984  2016                Hawaii        Kalawao County     15005
15267  2016              Virginia          Bedford city     51515
15284  2016              Virginia    Clifton Forge city     51560
15802  2020              Colorado     Broomfield County     08014
15871  2020  District of Columbia  District Of Columbia     11001
15870  2020  District of Columbia  District of Columbia     11000
16100  2020                Hawaii        Kalawao County     15005
18383  2020              Virginia          Bedford city     51515
18400  2020              Virginia    Clifton Forge city     51560

We've already explored problems with Bedford City, VA and Broomfield County, CO. Spelling mistakes and duplicated codes in DC are here again.

Clifton Forge, VA, is another former independent city that gave up its status, doing so in 2001. The dataset seems to contain a "ghost row" for it in 2004. Let's drop it.

But here we see another complication with Kalawao County, Hawaii. It was founded to resettle leprosy patients, and to this day non-residents may only visit with permission. The only land access is by mule. Though technically named a county, it does not have the powers of one, and is governed by Maui County. Thus it does not even appear in our initial election dataset. With a population of 82, it may be safe to drop.

In [45]:
education = education[~education['County'].str.contains("Broomfield County", na=False)]
education = education[~education['County'].str.contains("Bedford city", na=False)]
education = education[~education['County'].str.contains("Kalawao", na=False)]
education = education[~education['County'].str.contains("Clifton Forge city", na=False)]

education = education.replace({"District of Columbia": "District Of Columbia"})

In [46]:
# Define the key columns to compare
key_cols = ['Year', 'State', 'County', 'FIPS Code']

# Find rows in education that are not in election_pivot
education_not_in_election = education.merge(
    election_pivot[key_cols].drop_duplicates(),
    on=key_cols,
    how='left',
    indicator=True
).query('_merge == "left_only"').drop(columns=['_merge'])

# Show the unique counties that are missing
missing_counties = education_not_in_election[['Year', 'State', 'County', 'FIPS Code']].drop_duplicates()

print(missing_counties.sort_values(by=['Year', 'State', 'County']))

       Year                 State                County FIPS Code
289    2000  District Of Columbia  District Of Columbia     11000
3401   2004  District Of Columbia  District Of Columbia     11000
6513   2008  District Of Columbia  District Of Columbia     11000
9625   2012  District Of Columbia  District Of Columbia     11000
12737  2016  District Of Columbia  District Of Columbia     11000
15849  2020  District Of Columbia  District Of Columbia     11000

In [47]:
education = education[~((education['State'] == 'District Of Columbia') & (education['FIPS Code'] == '11000'))]

In [48]:
education

,Year,State,County,FIPS Code,At least some college,Bachelor's degree or higher,High school graduate,Less than high school
0,2000,Alabama,Autauga County,01001,44.900000,18.000000,78.700000,21.300000
1,2000,Alabama,Baldwin County,01003,52.400000,23.100000,82.000000,18.000000
2,2000,Alabama,Barbour County,01005,32.200000,10.900000,64.600000,35.300000
3,2000,Alabama,Bibb County,01007,27.500000,7.100000,63.200000,36.800000
4,2000,Alabama,Blount County,01009,34.400000,9.600000,70.400000,29.600000
...,...,...,...,...,...,...,...,...
18691,2020,Wyoming,Sweetwater County,56037,60.738243,20.069467,92.326898,7.673102
18692,2020,Wyoming,Teton County,56039,80.223940,60.108324,97.060793,2.939207
18693,2020,Wyoming,Uinta County,56041,58.134929,21.042262,94.030149,5.969851
18694,2020,Wyoming,Washakie County,56043,60.902534,22.151219,91.362635,8.637365
18695,2020,Wyoming,Weston County,56045,54.964355,17.993430,91.561893,8.438107

In [49]:
election_pivot = pd.merge(
    election_pivot,
    education[['Year', 'State', 'County', 'FIPS Code', "Bachelor's degree or higher", "At least some college", "High school graduate", "Less than high school"]],
    on=['Year', 'State', 'County', 'FIPS Code'],
    how='left'
)

In [50]:
election_pivot = election_pivot.round(2)
election_pivot

,Year,State,County,FIPS Code,Democrat Votes,Democrat Percentage,Republican Votes,Republican Percentage,Other Votes,Other Percentage,Total Votes,D-R margin,Two party vote share,Unemployment rate,Bachelor's degree or higher,At least some college,High school graduate,Less than high school
0,2000,Alabama,Autauga County,01001,4942,28.72,11993,69.69,273,1.59,17208,-40.97,98.41,4.1,18.00,44.90,78.70,21.30
1,2000,Alabama,Baldwin County,01003,13997,24.78,40872,72.37,1611,2.85,56480,-47.59,97.15,3.7,23.10,52.40,82.00,18.00
2,2000,Alabama,Barbour County,01005,5188,49.91,5096,49.02,111,1.07,10395,0.89,98.93,5.6,10.90,32.20,64.60,35.30
3,2000,Alabama,Bibb County,01007,2710,38.16,4273,60.17,118,1.66,7101,-22.01,98.33,5.4,7.10,27.50,63.20,36.80
4,2000,Alabama,Blount County,01009,4977,27.69,12667,70.48,329,1.83,17973,-42.79,98.17,3.5,9.60,34.40,70.40,29.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18661,2020,Wyoming,Sweetwater County,56037,3823,22.89,12229,73.24,646,3.87,16698,-50.35,96.13,7.5,20.07,60.74,92.33,7.67
18662,2020,Wyoming,Teton County,56039,9848,66.60,4341,29.36,598,4.04,14787,37.24,95.96,5.9,60.11,80.22,97.06,2.94
18663,2020,Wyoming,Uinta County,56041,1591,16.82,7496,79.25,372,3.93,9459,-62.43,96.07,6.4,21.04,58.13,94.03,5.97
18664,2020,Wyoming,Washakie County,56043,651,16.15,3245,80.48,136,3.37,4032,-64.33,96.63,5.3,22.15,60.90,91.36,8.64
18665,2020,Wyoming,Weston County,56045,360,10.11,3107,87.28,93,2.61,3560,-77.17,97.39,3.9,17.99,54.96,91.56,8.44

# COMBINING WITH POPULATION
This will also allow us to calculate turnout with total votes.

In [51]:
population = pd.read_csv("/Users/matthewcavanaugh/Desktop/GitHub/us-presidential-elections-by-county/sources/Population CLEANED.csv")
population

       Year    State             County  Population
0      2000  Alabama     Autauga County       43751
1      2000  Alabama     Baldwin County      140416
2      2000  Alabama     Barbour County       29042
3      2000  Alabama        Bibb County       19856
4      2000  Alabama      Blount County       50982
...     ...      ...                ...         ...
18661  2020  Wyoming  Sweetwater County       42271
18662  2020  Wyoming       Teton County       23324
18663  2020  Wyoming       Uinta County       20447
18664  2020  Wyoming    Washakie County        7683
18665  2020  Wyoming      Weston County        6838

[18666 rows x 4 columns]

In [52]:
pop_keys = population[['State', 'County']].copy()
elec_keys = election_pivot[['State', 'County']].copy()

# Normalize by stripping whitespace and converting to lowercase for comparison only
pop_keys['State_norm'] = pop_keys['State'].str.strip().str.lower()
pop_keys['County_norm'] = pop_keys['County'].str.strip().str.lower()

elec_keys['State_norm'] = elec_keys['State'].str.strip().str.lower()
elec_keys['County_norm'] = elec_keys['County'].str.strip().str.lower()

pop_set = set(pop_keys[['State_norm', 'County_norm']].apply(tuple, axis=1))
elec_set = set(elec_keys[['State_norm', 'County_norm']].apply(tuple, axis=1))

only_in_population = pop_set - elec_set
only_in_election = elec_set - pop_set

print("In population but NOT in election_pivot:")
for state, county in sorted(only_in_population):
    # Get original names from population dataframe (case sensitive)
    original = pop_keys[(pop_keys['State_norm'] == state) & (pop_keys['County_norm'] == county)]
    print(original[['State', 'County']].values[0])

print("\nIn election_pivot but NOT in population:")
for state, county in sorted(only_in_election):
    # Get original names from election_pivot dataframe
    original = elec_keys[(elec_keys['State_norm'] == state) & (elec_keys['County_norm'] == county)]
    print(original[['State', 'County']].values[0])

In population but NOT in election_pivot:
['New Mexico' 'Doña Ana County']

In election_pivot but NOT in population:
['New Mexico' 'Dona Ana County']

Just some spelling errors. Easily fixable.

In [53]:
# Define a mapping of old county names to your preferred names for 'population' df
county_name_corrections = {
    'La Salle Parish': 'Lasalle Parish',
    'Saint Louis County': 'St. Louis County',
    'Doña Ana County': 'Dona Ana County'
}

# Apply corrections
population['County'] = population['County'].replace(county_name_corrections)
election_pivot['County'] = election_pivot['County'].replace(county_name_corrections)

In [54]:
pop_keys = population[['State', 'County']].copy()
elec_keys = election_pivot[['State', 'County']].copy()

# Normalize by stripping whitespace and converting to lowercase for comparison only
pop_keys['State_norm'] = pop_keys['State'].str.strip().str.lower()
pop_keys['County_norm'] = pop_keys['County'].str.strip().str.lower()

elec_keys['State_norm'] = elec_keys['State'].str.strip().str.lower()
elec_keys['County_norm'] = elec_keys['County'].str.strip().str.lower()

pop_set = set(pop_keys[['State_norm', 'County_norm']].apply(tuple, axis=1))
elec_set = set(elec_keys[['State_norm', 'County_norm']].apply(tuple, axis=1))

only_in_population = pop_set - elec_set
only_in_election = elec_set - pop_set

print("In population but NOT in election_pivot:")
for state, county in sorted(only_in_population):
    # Get original names from population dataframe (case sensitive)
    original = pop_keys[(pop_keys['State_norm'] == state) & (pop_keys['County_norm'] == county)]
    print(original[['State', 'County']].values[0])

print("\nIn election_pivot but NOT in population:")
for state, county in sorted(only_in_election):
    # Get original names from election_pivot dataframe
    original = elec_keys[(elec_keys['State_norm'] == state) & (elec_keys['County_norm'] == county)]
    print(original[['State', 'County']].values[0])

In population but NOT in election_pivot:

In election_pivot but NOT in population:

Finally ready to merge!

In [55]:
election_pivot = pd.merge(
    population,
    election_pivot,
    on=['State', 'County', 'Year'],
    how='inner'
)

In [56]:
election_pivot

,Year,State,County,Population,FIPS Code,Democrat Votes,Democrat Percentage,Republican Votes,Republican Percentage,Other Votes,Other Percentage,Total Votes,D-R margin,Two party vote share,Unemployment rate,Bachelor's degree or higher,At least some college,High school graduate,Less than high school
0,2000,Alabama,Autauga County,43751,01001,4942,28.72,11993,69.69,273,1.59,17208,-40.97,98.41,4.1,18.00,44.90,78.70,21.30
1,2000,Alabama,Baldwin County,140416,01003,13997,24.78,40872,72.37,1611,2.85,56480,-47.59,97.15,3.7,23.10,52.40,82.00,18.00
2,2000,Alabama,Barbour County,29042,01005,5188,49.91,5096,49.02,111,1.07,10395,0.89,98.93,5.6,10.90,32.20,64.60,35.30
3,2000,Alabama,Bibb County,19856,01007,2710,38.16,4273,60.17,118,1.66,7101,-22.01,98.33,5.4,7.10,27.50,63.20,36.80
4,2000,Alabama,Blount County,50982,01009,4977,27.69,12667,70.48,329,1.83,17973,-42.79,98.17,3.5,9.60,34.40,70.40,29.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18661,2020,Wyoming,Sweetwater County,42271,56037,3823,22.89,12229,73.24,646,3.87,16698,-50.35,96.13,7.5,20.07,60.74,92.33,7.67
18662,2020,Wyoming,Teton County,23324,56039,9848,66.60,4341,29.36,598,4.04,14787,37.24,95.96,5.9,60.11,80.22,97.06,2.94
18663,2020,Wyoming,Uinta County,20447,56041,1591,16.82,7496,79.25,372,3.93,9459,-62.43,96.07,6.4,21.04,58.13,94.03,5.97
18664,2020,Wyoming,Washakie County,7683,56043,651,16.15,3245,80.48,136,3.37,4032,-64.33,96.63,5.3,22.15,60.90,91.36,8.64
18665,2020,Wyoming,Weston County,6838,56045,360,10.11,3107,87.28,93,2.61,3560,-77.17,97.39,3.9,17.99,54.96,91.56,8.44

Calculate a new turnout column.

In [57]:
election_pivot['Turnout'] = (election_pivot['Total Votes'] / election_pivot['Population']) * 100

In [58]:
election_pivot.isnull().sum()

Year                           0
State                          0
County                         0
Population                     0
FIPS Code                      0
Democrat Votes                 0
Democrat Percentage            0
Republican Votes               0
Republican Percentage          0
Other Votes                    0
Other Percentage               0
Total Votes                    0
D-R margin                     0
Two party vote share           0
Unemployment rate              0
Bachelor's degree or higher    0
At least some college          0
High school graduate           0
Less than high school          0
Turnout                        0
dtype: int64

# Any other columns I can add?

# Reorder columns?

Reorder columns for aesthetic purposes.

In [59]:
election_pivot = election_pivot[[
    'Year', 
    'State', 
    'County', 
    'FIPS Code', 
    'Population',
    'Democrat Votes', 
    'Democrat Percentage', 
    'Republican Votes', 
    'Republican Percentage',
    'Other Votes',
    'Other Percentage',
    'Total Votes',
    'Turnout',
    'D-R margin',
    'Two party vote share',
    "Bachelor's degree or higher",
    'At least some college',
    'High school graduate',
    'Less than high school',
    'Unemployment rate'
]]

In [60]:
election_pivot = election_pivot.round(2)
election_pivot

,Year,State,County,FIPS Code,Population,Democrat Votes,Democrat Percentage,Republican Votes,Republican Percentage,Other Votes,Other Percentage,Total Votes,Turnout,D-R margin,Two party vote share,Bachelor's degree or higher,At least some college,High school graduate,Less than high school,Unemployment rate
0,2000,Alabama,Autauga County,01001,43751,4942,28.72,11993,69.69,273,1.59,17208,39.33,-40.97,98.41,18.00,44.90,78.70,21.30,4.1
1,2000,Alabama,Baldwin County,01003,140416,13997,24.78,40872,72.37,1611,2.85,56480,40.22,-47.59,97.15,23.10,52.40,82.00,18.00,3.7
2,2000,Alabama,Barbour County,01005,29042,5188,49.91,5096,49.02,111,1.07,10395,35.79,0.89,98.93,10.90,32.20,64.60,35.30,5.6
3,2000,Alabama,Bibb County,01007,19856,2710,38.16,4273,60.17,118,1.66,7101,35.76,-22.01,98.33,7.10,27.50,63.20,36.80,5.4
4,2000,Alabama,Blount County,01009,50982,4977,27.69,12667,70.48,329,1.83,17973,35.25,-42.79,98.17,9.60,34.40,70.40,29.60,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18661,2020,Wyoming,Sweetwater County,56037,42271,3823,22.89,12229,73.24,646,3.87,16698,39.50,-50.35,96.13,20.07,60.74,92.33,7.67,7.5
18662,2020,Wyoming,Teton County,56039,23324,9848,66.60,4341,29.36,598,4.04,14787,63.40,37.24,95.96,60.11,80.22,97.06,2.94,5.9
18663,2020,Wyoming,Uinta County,56041,20447,1591,16.82,7496,79.25,372,3.93,9459,46.26,-62.43,96.07,21.04,58.13,94.03,5.97,6.4
18664,2020,Wyoming,Washakie County,56043,7683,651,16.15,3245,80.48,136,3.37,4032,52.48,-64.33,96.63,22.15,60.90,91.36,8.64,5.3
18665,2020,Wyoming,Weston County,56045,6838,360,10.11,3107,87.28,93,2.61,3560,52.06,-77.17,97.39,17.99,54.96,91.56,8.44,3.9

In [61]:
expected_years = {2000, 2004, 2008, 2012, 2016, 2020}

# Find which years exist per (State, County)
year_counts = (
    election_pivot
    .groupby(['State', 'County'])['Year']
    .agg(lambda years: set(years))
    .reset_index()
)

# Add a column with missing years
year_counts['MissingYears'] = year_counts['Year'].apply(lambda years: expected_years - years)

# Filter for counties that are missing at least one year
missing_years_df = year_counts[year_counts['MissingYears'].apply(len) > 0]

# Preview the results
print(missing_years_df[['State', 'County', 'MissingYears']])

Empty DataFrame
Columns: [State, County, MissingYears]
Index: []

# EXPORTING THE COMPLETE DATASET.

In [62]:
file_path = '/Users/matthewcavanaugh/Desktop/GitHub/us-presidential-elections-by-county/Cleaned County Dataset.csv'
election_pivot.to_csv(file_path, index=False)