In [60]:
import pandas as pd

In [61]:
education = pd.read_csv("/Users/matthewcavanaugh/Desktop/GitHub/us-presidential-elections-by-county/sources/Education2023.csv", encoding='latin1')
education

,FIPS Code,State,Area name,Attribute,Value
0,0,US,United States,"Less than a high school diploma, 1970",5.237331e+07
1,0,US,United States,"High school diploma only, 1970",3.415805e+07
2,0,US,United States,"Some college (1-3 years), 1970",1.165073e+07
3,0,US,United States,"Four years of college or higher, 1970",1.171727e+07
4,0,US,United States,Percent of adults with less than a high school...,4.770000e+01
...,...,...,...,...,...
169240,72153,PR,Yauco Municipio,"Bachelor's degree or higher, 2019-23",6.874000e+03
169241,72153,PR,Yauco Municipio,Percent of adults who are not high school grad...,2.048521e+01
169242,72153,PR,Yauco Municipio,Percent of adults who are high school graduate...,3.396055e+01
169243,72153,PR,Yauco Municipio,Percent of adults completing some college or a...,1.843787e+01
169244,72153,PR,Yauco Municipio,Percent of adults with a bachelor's degree or ...,2.711637e+01

Our dataset provides data for 2000, 2008-2012, and 2019-23.

We will assign 2008-12 values to 2010, and 2019-23 values to 2021.

Then using values from 2000, 2010, and 2021, we will interpolate estimated values for all other years, and then take only the ones we need (election years from 2000 to 2021).

In [62]:
education['Attribute'].value_counts()

Attribute
Less than high school graduate, 2019-23                                     3275
Some college or associate degree, 2019-23                                   3275
Percent of adults with a bachelor's degree or higher, 2019-23               3275
Percent of adults completing some college or associate degree, 2019-23      3275
Percent of adults who are high school graduates (or equivalent), 2019-23    3275
Percent of adults who are not high school graduates, 2019-23                3275
Bachelor's degree or higher, 2019-23                                        3275
High school graduate (or equivalency), 2019-23                              3275
Some college or associate degree, 2008-12                                   3274
Less than high school graduate, 2008-12                                     3274
High school graduate (or equivalency), 2008-12                              3274
Bachelor's degree or higher, 2008-12                                        3274
Percent of adults who are not high school graduates, 2008-12                3274
Percent of adults who are high school graduates (or equivalent), 2008-12    3274
Percent of adults completing some college or associate degree, 2008-12      3274
Percent of adults with a bachelor's degree or higher, 2008-12               3274
Less than high school graduate, 2000                                        3272
Percent of adults with a bachelor's degree or higher, 2000                  3272
Percent of adults completing some college or associate degree, 2000         3272
Percent of adults who are high school graduates (or equivalent), 2000       3272
Percent of adults who are not high school graduates, 2000                   3272
Bachelor's degree or higher, 2000                                           3272
High school graduate (or equivalency), 2000                                 3272
Some college or associate degree, 2000                                      3272
Percent of adults with a bachelor's degree or higher, 1990                  3271
Some college or associate degree, 1990                                      3271
Less than high school graduate, 1990                                        3271
High school graduate (or equivalency), 1990                                 3271
Percent of adults who are not high school graduates, 1990                   3271
Bachelor's degree or higher, 1990                                           3271
Percent of adults who are high school graduates (or equivalent), 1990       3271
Percent of adults completing some college or associate degree, 1990         3270
Percent of adults completing four years of college or higher, 1980          3267
Percent of adults with a high school diploma only, 1980                     3267
Percent of adults with less than a high school diploma, 1980                3267
Four years of college or higher, 1980                                       3267
Some college (1-3 years), 1980                                              3267
High school diploma only, 1980                                              3267
Less than a high school diploma, 1980                                       3267
Percent of adults completing some college (1-3 years), 1980                 3267
2024 Urban Influence Code                                                   3222
2023 Rural-urban Continuum Code                                             3222
2013 Urban Influence Code                                                   3221
2013 Rural-urban Continuum Code                                             3221
High school diploma only, 1970                                              3186
Percent of adults completing four years of college or higher, 1970          3186
Percent of adults completing some college (1-3 years), 1970                 3186
Percent of adults with a high school diploma only, 1970                     3186
Percent of adults with less than a high school diploma, 1970                3186
Four years of college or higher, 1970                                       3186
Some college (1-3 years), 1970                                              3186
Less than a high school diploma, 1970                                       3186
Name: count, dtype: int64

In [63]:
values_to_keep = [
    "Percent of adults who are not high school graduates, 2000", 
"Percent of adults who are high school graduates (or equivalent), 2000", 
"Percent of adults completing some college or associate degree, 2000",
"Percent of adults with a bachelor's degree or higher, 2000",
    
"Percent of adults who are not high school graduates, 2008-12",              
"Percent of adults who are high school graduates (or equivalent), 2008-12",   
"Percent of adults completing some college or associate degree, 2008-12",    
"Percent of adults with a bachelor's degree or higher, 2008-12", 
    
"Percent of adults with a bachelor's degree or higher, 2019-23",              
"Percent of adults completing some college or associate degree, 2019-23",
"Percent of adults who are high school graduates (or equivalent), 2019-23",
"Percent of adults who are not high school graduates, 2019-23"
]

education = education[education['Attribute'].isin(values_to_keep)]

In [64]:
education

,FIPS Code,State,Area name,Attribute,Value
28,0,US,United States,Percent of adults who are not high school grad...,19.600000
29,0,US,United States,Percent of adults who are high school graduate...,28.600000
30,0,US,United States,Percent of adults completing some college or a...,27.400000
31,0,US,United States,Percent of adults with a bachelor's degree or ...,24.400000
36,0,US,United States,Percent of adults who are not high school grad...,14.280311
...,...,...,...,...,...
169236,72153,PR,Yauco Municipio,Percent of adults with a bachelor's degree or ...,16.795075
169241,72153,PR,Yauco Municipio,Percent of adults who are not high school grad...,20.485207
169242,72153,PR,Yauco Municipio,Percent of adults who are high school graduate...,33.960552
169243,72153,PR,Yauco Municipio,Percent of adults completing some college or a...,18.437870
169244,72153,PR,Yauco Municipio,Percent of adults with a bachelor's degree or ...,27.116371

In [65]:
education['Attribute'].value_counts()

Attribute
Percent of adults who are not high school graduates, 2019-23                3275
Percent of adults who are high school graduates (or equivalent), 2019-23    3275
Percent of adults completing some college or associate degree, 2019-23      3275
Percent of adults with a bachelor's degree or higher, 2019-23               3275
Percent of adults who are not high school graduates, 2008-12                3274
Percent of adults who are high school graduates (or equivalent), 2008-12    3274
Percent of adults completing some college or associate degree, 2008-12      3274
Percent of adults with a bachelor's degree or higher, 2008-12               3274
Percent of adults who are not high school graduates, 2000                   3272
Percent of adults who are high school graduates (or equivalent), 2000       3272
Percent of adults completing some college or associate degree, 2000         3272
Percent of adults with a bachelor's degree or higher, 2000                  3272
Name: count, dtype: int64

Rename columns for processing

In [66]:
education['Attribute'] = education['Attribute'].str.replace("Percent of adults who are not high school graduates, 2019-23", "Less than high school, 2021")
education['Attribute'] = education['Attribute'].str.replace("Percent of adults who are high school graduates (or equivalent), 2019-23", "High school graduate, 2021")
education['Attribute'] = education['Attribute'].str.replace("Percent of adults completing some college or associate degree, 2019-23", "At least some college, 2021")
education['Attribute'] = education['Attribute'].str.replace("Percent of adults with a bachelor's degree or higher, 2019-23", "Bachelor's degree or higher, 2021")
education['Attribute'] = education['Attribute'].str.replace("Percent of adults who are not high school graduates, 2008-12", "Less than high school, 2010")
education['Attribute'] = education['Attribute'].str.replace("Percent of adults who are high school graduates (or equivalent), 2008-12", "High school graduate, 2010")
education['Attribute'] = education['Attribute'].str.replace("Percent of adults completing some college or associate degree, 2008-12", "At least some college, 2010")
education['Attribute'] = education['Attribute'].str.replace("Percent of adults with a bachelor's degree or higher, 2008-12", "Bachelor's degree or higher, 2010")
education['Attribute'] = education['Attribute'].str.replace("Percent of adults who are not high school graduates, 2000", "Less than high school, 2000")
education['Attribute'] = education['Attribute'].str.replace("Percent of adults who are high school graduates (or equivalent), 2000", "High school graduate, 2000")
education['Attribute'] = education['Attribute'].str.replace("Percent of adults completing some college or associate degree, 2000", "At least some college, 2000")
education['Attribute'] = education['Attribute'].str.replace("Percent of adults with a bachelor's degree or higher, 2000", "Bachelor's degree or higher, 2000")

/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/3597116346.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education['Attribute'] = education['Attribute'].str.replace("Percent of adults who are not high school graduates, 2019-23", "Less than high school, 2021")
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/3597116346.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education['Attribute'] = education['Attribute'].str.replace("Percent of adults who are high school graduates (or equivalent), 2019-23", "High school graduate, 2021")
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/3597116346.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education['Attribute'] = education['Attribute'].str.replace("Percent of adults completing some college or associate degree, 2019-23", "At least some college, 2021")
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/3597116346.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education['Attribute'] = education['Attribute'].str.replace("Percent of adults with a bachelor's degree or higher, 2019-23", "Bachelor's degree or higher, 2021")
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/3597116346.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education['Attribute'] = education['Attribute'].str.replace("Percent of adults who are not high school graduates, 2008-12", "Less than high school, 2010")
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/3597116346.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education['Attribute'] = education['Attribute'].str.replace("Percent of adults who are high school graduates (or equivalent), 2008-12", "High school graduate, 2010")
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/3597116346.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education['Attribute'] = education['Attribute'].str.replace("Percent of adults completing some college or associate degree, 2008-12", "At least some college, 2010")
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/3597116346.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education['Attribute'] = education['Attribute'].str.replace("Percent of adults with a bachelor's degree or higher, 2008-12", "Bachelor's degree or higher, 2010")
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/3597116346.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education['Attribute'] = education['Attribute'].str.replace("Percent of adults who are not high school graduates, 2000", "Less than high school, 2000")
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/3597116346.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education['Attribute'] = education['Attribute'].str.replace("Percent of adults who are high school graduates (or equivalent), 2000", "High school graduate, 2000")
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/3597116346.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education['Attribute'] = education['Attribute'].str.replace("Percent of adults completing some college or associate degree, 2000", "At least some college, 2000")
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/3597116346.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education['Attribute'] = education['Attribute'].str.replace("Percent of adults with a bachelor's degree or higher, 2000", "Bachelor's degree or higher, 2000")

In [67]:
education

,FIPS Code,State,Area name,Attribute,Value
28,0,US,United States,"Less than high school, 2000",19.600000
29,0,US,United States,"High school graduate, 2000",28.600000
30,0,US,United States,"At least some college, 2000",27.400000
31,0,US,United States,"Bachelor's degree or higher, 2000",24.400000
36,0,US,United States,"Less than high school, 2010",14.280311
...,...,...,...,...,...
169236,72153,PR,Yauco Municipio,"Bachelor's degree or higher, 2010",16.795075
169241,72153,PR,Yauco Municipio,"Less than high school, 2021",20.485207
169242,72153,PR,Yauco Municipio,"High school graduate, 2021",33.960552
169243,72153,PR,Yauco Municipio,"At least some college, 2021",18.437870
169244,72153,PR,Yauco Municipio,"Bachelor's degree or higher, 2021",27.116371

In [68]:
education['Attribute'].value_counts()

Attribute
Less than high school, 2021          3275
High school graduate, 2021           3275
At least some college, 2021          3275
Bachelor's degree or higher, 2021    3275
Less than high school, 2010          3274
High school graduate, 2010           3274
At least some college, 2010          3274
Bachelor's degree or higher, 2010    3274
Less than high school, 2000          3272
High school graduate, 2000           3272
At least some college, 2000          3272
Bachelor's degree or higher, 2000    3272
Name: count, dtype: int64

In [69]:
education[education['Attribute'].str.endswith(', 2000')].shape

(13088, 5)

In [70]:
# Split into description and year
education[['Attribute', 'Year']] = education['Attribute'].str.extract(r'^(.*),\s*(\d{4})$')

education

/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/1663415474.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education[['Attribute', 'Year']] = education['Attribute'].str.extract(r'^(.*),\s*(\d{4})$')
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/1663415474.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  education[['Attribute', 'Year']] = education['Attribute'].str.extract(r'^(.*),\s*(\d{4})$')

,FIPS Code,State,Area name,Attribute,Value,Year
28,0,US,United States,Less than high school,19.600000,2000
29,0,US,United States,High school graduate,28.600000,2000
30,0,US,United States,At least some college,27.400000,2000
31,0,US,United States,Bachelor's degree or higher,24.400000,2000
36,0,US,United States,Less than high school,14.280311,2010
...,...,...,...,...,...,...
169236,72153,PR,Yauco Municipio,Bachelor's degree or higher,16.795075,2010
169241,72153,PR,Yauco Municipio,Less than high school,20.485207,2021
169242,72153,PR,Yauco Municipio,High school graduate,33.960552,2021
169243,72153,PR,Yauco Municipio,At least some college,18.437870,2021
169244,72153,PR,Yauco Municipio,Bachelor's degree or higher,27.116371,2021

In [71]:
# Drop national and state aggregates, only keep county equivalents
education = education[education['Area name'].str.contains('County|City|city|Parish|District of Columbia', na=False)]

In [72]:
# Drop Alaska
education = education[~education['State'].str.contains('AK', na=False)]

In [73]:
education_pivoted = education.pivot_table(
    index=["FIPS Code", "Year", "State", "Area name"],
    # or just 'County' if there's no year
    columns="Attribute",
    values="Value"
).reset_index()

education_pivoted = education_pivoted.rename_axis(None, axis=1)
education_pivoted

,FIPS Code,Year,State,Area name,At least some college,Bachelor's degree or higher,High school graduate,Less than high school
0,1001,2000,AL,Autauga County,26.900000,18.000000,33.800000,21.300000
1,1001,2010,AL,Autauga County,29.618143,21.707831,33.786706,14.887321
2,1001,2021,AL,Autauga County,29.320284,28.282680,32.675939,9.721098
3,1003,2000,AL,Baldwin County,29.300000,23.100000,29.600000,18.000000
4,1003,2010,AL,Baldwin County,31.819503,27.741591,28.816463,11.622443
...,...,...,...,...,...,...,...,...
9331,56043,2010,WY,Washakie County,35.062865,23.339826,32.388879,9.208429
9332,56043,2021,WY,Washakie County,39.120160,22.032358,30.267224,8.580258
9333,56045,2000,WY,Weston County,30.500000,14.500000,40.200000,14.800000
9334,56045,2010,WY,Weston County,35.731560,17.492946,37.948408,8.827086
9335,56045,2021,WY,Weston County,37.094862,18.043478,36.462451,8.399209

In [74]:
education_pivoted['Year'] = education_pivoted['Year'].astype(int)
education_pivoted.rename(columns={'Area name': 'County'}, inplace=True)
education_pivoted = education_pivoted[['Year', 'State', 'County', 'FIPS Code', 'At least some college', "Bachelor's degree or higher", 'High school graduate', 'Less than high school']]

state_abbrevs = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',
    'DC': 'District of Columbia',
    'AS': 'American Samoa',
    'GU': 'Guam',
    'MP': 'Northern Mariana Islands',
    'PR': 'Puerto Rico',
    'VI': 'Virgin Islands'
}
education_pivoted['State'] = education_pivoted['State'].replace(state_abbrevs)

education_pivoted['High school graduate'] = education_pivoted['High school graduate'] + education_pivoted['At least some college'] + education_pivoted["Bachelor's degree or higher"]
education_pivoted['At least some college'] = education_pivoted['At least some college'] + education_pivoted["Bachelor's degree or higher"]

education_pivoted

,Year,State,County,FIPS Code,At least some college,Bachelor's degree or higher,High school graduate,Less than high school
0,2000,Alabama,Autauga County,1001,44.900000,18.000000,78.700000,21.300000
1,2010,Alabama,Autauga County,1001,51.325973,21.707831,85.112679,14.887321
2,2021,Alabama,Autauga County,1001,57.602963,28.282680,90.278902,9.721098
3,2000,Alabama,Baldwin County,1003,52.400000,23.100000,82.000000,18.000000
4,2010,Alabama,Baldwin County,1003,59.561094,27.741591,88.377557,11.622443
...,...,...,...,...,...,...,...,...
9331,2010,Wyoming,Washakie County,56043,58.402692,23.339826,90.791571,9.208429
9332,2021,Wyoming,Washakie County,56043,61.152518,22.032358,91.419742,8.580258
9333,2000,Wyoming,Weston County,56045,45.000000,14.500000,85.200000,14.800000
9334,2010,Wyoming,Weston County,56045,53.224506,17.492946,91.172914,8.827086
9335,2021,Wyoming,Weston County,56045,55.138340,18.043478,91.600791,8.399209

In [75]:
education_pivoted.head(10)

,Year,State,County,FIPS Code,At least some college,Bachelor's degree or higher,High school graduate,Less than high school
0,2000,Alabama,Autauga County,1001,44.900000,18.000000,78.700000,21.300000
1,2010,Alabama,Autauga County,1001,51.325973,21.707831,85.112679,14.887321
2,2021,Alabama,Autauga County,1001,57.602963,28.282680,90.278902,9.721098
3,2000,Alabama,Baldwin County,1003,52.400000,23.100000,82.000000,18.000000
4,2010,Alabama,Baldwin County,1003,59.561094,27.741591,88.377557,11.622443
5,2021,Alabama,Baldwin County,1003,64.189362,32.797637,91.731400,8.268600
6,2000,Alabama,Barbour County,1005,32.200000,10.900000,64.600000,35.300000
7,2010,Alabama,Barbour County,1005,40.296070,14.524286,73.590770,26.409230
8,2021,Alabama,Barbour County,1005,40.208759,11.464715,77.813705,22.186295
9,2000,Alabama,Bibb County,1007,27.500000,7.100000,63.200000,36.800000

We now have values for 2000, 2010, and 2021.

# Interpolate values for all other years
We will estimate 2001-2009 values based on 2000 and 2010 actual values, then estimate 2011-2020 based on 2010 and 2021 actual values. Then we will reduce to only the years we need.

In [78]:
import pandas as pd

numeric_cols = [
    'At least some college',
    "Bachelor's degree or higher",
    'High school graduate',
    'Less than high school'
]

def interpolate_piecewise(df):
    # For each county (FIPS), interpolate in two segments
    
    def interp_group(group):
        group = group.sort_values('Year').set_index('Year')
        
        # Part 1: 2000-2010
        part1 = group.loc[2000:2010].copy()
        part1 = part1.reindex(range(2000, 2011))
        # Fill FIPS Code and other static columns BEFORE interpolation
        part1['FIPS Code'] = group['FIPS Code'].iloc[0]
        part1['State'] = group['State'].iloc[0]
        part1['County'] = group['County'].iloc[0]
        part1[numeric_cols] = part1[numeric_cols].interpolate(method='linear')
        
        # Part 2: 2010-2021
        part2 = group.loc[2010:2021].copy()
        part2 = part2.reindex(range(2010, 2022))
        part2['FIPS Code'] = group['FIPS Code'].iloc[0]
        part2['State'] = group['State'].iloc[0]
        part2['County'] = group['County'].iloc[0]
        part2[numeric_cols] = part2[numeric_cols].interpolate(method='linear')
        
        # Combine, drop duplicated 2010 in part2
        part2 = part2.loc[2011:]
        combined = pd.concat([part1, part2])
        
        combined = combined.reset_index()
        return combined
    
    result = df.groupby('FIPS Code', group_keys=False).apply(interp_group)
    return result

# Apply
education_interpolated_piecewise = interpolate_piecewise(education_pivoted)
education_pivoted = education_interpolated_piecewise

/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_14754/3354247395.py:42: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('FIPS Code', group_keys=False).apply(interp_group)

In [79]:
education_pivoted

,Year,State,County,FIPS Code,At least some college,Bachelor's degree or higher,High school graduate,Less than high school
0,2000,Alabama,Autauga County,1001,44.900000,18.000000,78.700000,21.300000
1,2001,Alabama,Autauga County,1001,45.542597,18.370783,79.341268,20.658732
2,2002,Alabama,Autauga County,1001,46.185195,18.741566,79.982536,20.017464
3,2003,Alabama,Autauga County,1001,46.827792,19.112349,80.623804,19.376196
4,2004,Alabama,Autauga County,1001,47.470389,19.483132,81.265072,18.734928
...,...,...,...,...,...,...,...,...
17,2017,Wyoming,Weston County,56045,54.442400,17.843285,91.445199,8.554801
18,2018,Wyoming,Weston County,56045,54.616385,17.893333,91.484097,8.515903
19,2019,Wyoming,Weston County,56045,54.790370,17.943382,91.522995,8.477005
20,2020,Wyoming,Weston County,56045,54.964355,17.993430,91.561893,8.438107
21,2021,Wyoming,Weston County,56045,55.138340,18.043478,91.600791,8.399209

# Cut unneeded years

In [80]:
years_to_keep = [2000, 2004, 2008, 2012, 2016, 2020]
education_pivoted = education_pivoted[education_pivoted['Year'].isin(years_to_keep)]

In [81]:
education_pivoted

,Year,State,County,FIPS Code,At least some college,Bachelor's degree or higher,High school graduate,Less than high school
0,2000,Alabama,Autauga County,1001,44.900000,18.000000,78.700000,21.300000
4,2004,Alabama,Autauga County,1001,47.470389,19.483132,81.265072,18.734928
8,2008,Alabama,Autauga County,1001,50.040779,20.966265,83.830143,16.169857
12,2012,Alabama,Autauga County,1001,52.467244,22.903258,86.051992,13.948008
16,2016,Alabama,Autauga County,1001,54.749786,25.294112,87.930619,12.069381
...,...,...,...,...,...,...,...,...
4,2004,Wyoming,Weston County,56045,48.289802,15.697179,87.589166,12.410834
8,2008,Wyoming,Weston County,56045,51.579605,16.894357,89.978331,10.021669
12,2012,Wyoming,Weston County,56045,53.572476,17.593043,91.250710,8.749290
16,2016,Wyoming,Weston County,56045,54.268416,17.793237,91.406301,8.593699
20,2020,Wyoming,Weston County,56045,54.964355,17.993430,91.561893,8.438107

# Re - Sort

In [90]:
education_pivoted = education_pivoted.sort_values(by=['Year', 'State', 'County'])

In [91]:
education_pivoted

,Year,State,County,FIPS Code,At least some college,Bachelor's degree or higher,High school graduate,Less than high school
0,2000,Alabama,Autauga County,01001,44.900000,18.000000,78.700000,21.300000
0,2000,Alabama,Baldwin County,01003,52.400000,23.100000,82.000000,18.000000
0,2000,Alabama,Barbour County,01005,32.200000,10.900000,64.600000,35.300000
0,2000,Alabama,Bibb County,01007,27.500000,7.100000,63.200000,36.800000
0,2000,Alabama,Blount County,01009,34.400000,9.600000,70.400000,29.600000
...,...,...,...,...,...,...,...,...
20,2020,Wyoming,Sweetwater County,56037,60.738243,20.069467,92.326898,7.673102
20,2020,Wyoming,Teton County,56039,80.223940,60.108324,97.060793,2.939207
20,2020,Wyoming,Uinta County,56041,58.134929,21.042262,94.030149,5.969851
20,2020,Wyoming,Washakie County,56043,60.902534,22.151219,91.362635,8.637365
20,2020,Wyoming,Weston County,56045,54.964355,17.993430,91.561893,8.438107

In [92]:
education_pivoted['FIPS Code'] = education_pivoted['FIPS Code'].astype(str).str.zfill(5)

In [93]:
education_pivoted

,Year,State,County,FIPS Code,At least some college,Bachelor's degree or higher,High school graduate,Less than high school
0,2000,Alabama,Autauga County,01001,44.900000,18.000000,78.700000,21.300000
0,2000,Alabama,Baldwin County,01003,52.400000,23.100000,82.000000,18.000000
0,2000,Alabama,Barbour County,01005,32.200000,10.900000,64.600000,35.300000
0,2000,Alabama,Bibb County,01007,27.500000,7.100000,63.200000,36.800000
0,2000,Alabama,Blount County,01009,34.400000,9.600000,70.400000,29.600000
...,...,...,...,...,...,...,...,...
20,2020,Wyoming,Sweetwater County,56037,60.738243,20.069467,92.326898,7.673102
20,2020,Wyoming,Teton County,56039,80.223940,60.108324,97.060793,2.939207
20,2020,Wyoming,Uinta County,56041,58.134929,21.042262,94.030149,5.969851
20,2020,Wyoming,Washakie County,56043,60.902534,22.151219,91.362635,8.637365
20,2020,Wyoming,Weston County,56045,54.964355,17.993430,91.561893,8.438107

Let's try saving and combining for now.

In [94]:
# Specify the desired file path (e.g., in a 'data' subfolder)
file_path = '/Users/matthewcavanaugh/Desktop/GitHub/us-presidential-elections-by-county/sources/Education Cleaned.csv'

# Save the DataFrame to CSV at the specified path, without including the index
education_pivoted.to_csv(file_path, index=False)