In [24]:
import pandas as pd

In [25]:
unemployment = pd.read_csv("/Users/matthewcavanaugh/Desktop/GitHub/us-presidential-elections-by-county/sources/Unemployment2023.csv")
unemployment

,FIPS_Code,State,Area_Name,Attribute,Value
0,0,US,United States,Civilian_labor_force_2000,142601576.0
1,0,US,United States,Employed_2000,136904853.0
2,0,US,United States,Unemployed_2000,5696723.0
3,0,US,United States,Unemployment_rate_2000,4.0
4,0,US,United States,Civilian_labor_force_2001,143786537.0
...,...,...,...,...,...
329721,72153,PR,"Yauco Municipio, PR",Unemployment_rate_2022,10.3
329722,72153,PR,"Yauco Municipio, PR",Civilian_labor_force_2023,10488.0
329723,72153,PR,"Yauco Municipio, PR",Employed_2023,9278.0
329724,72153,PR,"Yauco Municipio, PR",Unemployed_2023,1210.0
329725,72153,PR,"Yauco Municipio, PR",Unemployment_rate_2023,11.5

In [26]:
# Split attribute into 'Attribute' and 'Year'
unemployment[['Attribute', 'Year']] = unemployment['Attribute'].str.extract(r'(.+?)_(\d{4})')

# Convert Year to integer
unemployment['Year'] = unemployment['Year'].astype(int)

In [27]:
# Drop national and state aggregates, only keep county equivalents
unemployment = unemployment[unemployment['Area_Name'].str.contains('County|City|city|Parish|District of Columbia', na=False)]

In [28]:
# Remove ", XX" at the end of the string
unemployment['Area_Name'] = unemployment['Area_Name'].str.replace(r',\s*[A-Z]{2}$', '', regex=True)

/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_12263/1912612501.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unemployment['Area_Name'] = unemployment['Area_Name'].str.replace(r',\s*[A-Z]{2}$', '', regex=True)

In [29]:
unemployment

,FIPS_Code,State,Area_Name,Attribute,Value,Year
195,1001,AL,Autauga County,Rural_Urban_Continuum_Code,2.0,2023
196,1001,AL,Autauga County,Urban_Influence_Code,2.0,2013
197,1001,AL,Autauga County,Metro,1.0,2023
198,1001,AL,Autauga County,Civilian_labor_force,21861.0,2000
199,1001,AL,Autauga County,Employed,20971.0,2000
...,...,...,...,...,...,...
322219,56045,WY,Weston County,Employed,3795.0,2023
322220,56045,WY,Weston County,Unemployed,81.0,2023
322221,56045,WY,Weston County,Unemployment_rate,2.1,2023
322222,56045,WY,Weston County,Median_Household_Income,67677.0,2022
322223,56045,WY,Weston County,Med_HH_Income_Percent_of_State_Total,95.0,2022

In [30]:
unemployment['Attribute'].value_counts()

Attribute
Civilian_labor_force                    74784
Employed                                74784
Unemployed                              74784
Unemployment_rate                       74784
Urban_Influence_Code                     3116
Median_Household_Income                  3109
Med_HH_Income_Percent_of_State_Total     3109
Rural_Urban_Continuum_Code               3108
Metro                                    3108
Name: count, dtype: int64

In [31]:
unemployment = unemployment[unemployment['Attribute'].str.contains('Unemployment_rate', na=False)]

In [32]:
unemployment.rename(columns={'Value': 'Unemployment rate'}, inplace=True)
unemployment.drop('Attribute', axis=1, inplace=True)
unemployment

/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_12263/910044994.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unemployment.rename(columns={'Value': 'Unemployment rate'}, inplace=True)
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_12263/910044994.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unemployment.drop('Attribute', axis=1, inplace=True)

        FIPS_Code State       Area_Name  Unemployment rate  Year
201          1001    AL  Autauga County                4.1  2000
205          1001    AL  Autauga County                4.1  2001
209          1001    AL  Autauga County                4.8  2002
213          1001    AL  Autauga County                5.0  2003
217          1001    AL  Autauga County                4.7  2004
...           ...   ...             ...                ...   ...
322205      56045    WY   Weston County                3.0  2019
322209      56045    WY   Weston County                3.9  2020
322213      56045    WY   Weston County                3.2  2021
322217      56045    WY   Weston County                2.6  2022
322221      56045    WY   Weston County                2.1  2023

[74784 rows x 5 columns]

In [33]:
unemployment['State'].nunique()

51

Drop Alaska

In [34]:
#unemployment = unemployment[~unemployment['State'].str.contains('AK', na=False)]

In [35]:
unemployment['State'].nunique()

51

In [36]:
state_abbrevs = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',
    'DC': 'District of Columbia',
    'AS': 'American Samoa',
    'GU': 'Guam',
    'MP': 'Northern Mariana Islands',
    'PR': 'Puerto Rico',
    'VI': 'Virgin Islands'
}

In [37]:
unemployment['State'] = unemployment['State'].replace(state_abbrevs)

/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_12263/3303815936.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unemployment['State'] = unemployment['State'].replace(state_abbrevs)

In [38]:
unemployment

        FIPS_Code    State       Area_Name  Unemployment rate  Year
201          1001  Alabama  Autauga County                4.1  2000
205          1001  Alabama  Autauga County                4.1  2001
209          1001  Alabama  Autauga County                4.8  2002
213          1001  Alabama  Autauga County                5.0  2003
217          1001  Alabama  Autauga County                4.7  2004
...           ...      ...             ...                ...   ...
322205      56045  Wyoming   Weston County                3.0  2019
322209      56045  Wyoming   Weston County                3.9  2020
322213      56045  Wyoming   Weston County                3.2  2021
322217      56045  Wyoming   Weston County                2.6  2022
322221      56045  Wyoming   Weston County                2.1  2023

[74784 rows x 5 columns]

Reduce down to only the years we need (election years)

In [39]:
election_years = [2000, 2004, 2008, 2012, 2016, 2020]
unemployment = unemployment[unemployment['Year'].isin(election_years)]

In [40]:
unemployment.rename(columns={'FIPS_Code': 'FIPS Code'}, inplace=True)
unemployment.rename(columns={'Area_Name': 'County'}, inplace=True)
unemployment

/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_12263/2646842961.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unemployment.rename(columns={'FIPS_Code': 'FIPS Code'}, inplace=True)
/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_12263/2646842961.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unemployment.rename(columns={'Area_Name': 'County'}, inplace=True)

        FIPS Code    State          County  Unemployment rate  Year
201          1001  Alabama  Autauga County                4.1  2000
217          1001  Alabama  Autauga County                4.7  2004
233          1001  Alabama  Autauga County                5.3  2008
249          1001  Alabama  Autauga County                7.1  2012
265          1001  Alabama  Autauga County                5.1  2016
...           ...      ...             ...                ...   ...
322145      56045  Wyoming   Weston County                4.0  2004
322161      56045  Wyoming   Weston County                3.1  2008
322177      56045  Wyoming   Weston County                4.2  2012
322193      56045  Wyoming   Weston County                5.0  2016
322209      56045  Wyoming   Weston County                3.9  2020

[18699 rows x 5 columns]

In [41]:
unemployment[unemployment['State'].str.contains('Dist')]

,FIPS Code,State,County,Unemployment rate,Year
33047,11000,District of Columbia,District of Columbia,5.7,2000
33063,11000,District of Columbia,District of Columbia,8.1,2004
33079,11000,District of Columbia,District of Columbia,6.8,2008
33095,11000,District of Columbia,District of Columbia,9.0,2012
33111,11000,District of Columbia,District of Columbia,6.2,2016
33127,11000,District of Columbia,District of Columbia,7.9,2020
33148,11001,District of Columbia,District of Columbia,5.7,2000
33164,11001,District of Columbia,District of Columbia,8.1,2004
33180,11001,District of Columbia,District of Columbia,6.8,2008
33196,11001,District of Columbia,District of Columbia,9.0,2012
33212,11001,District of Columbia,District of Columbia,6.2,2016
33228,11001,District of Columbia,District of Columbia,7.9,2020

In [44]:
virginia = unemployment[unemployment['State'].str.contains('Virginia')]
virginia['County'].value_counts()

County
Accomack County        6
Virginia Beach city    6
Petersburg city        6
Poquoson city          6
Portsmouth city        6
                      ..
Nottoway County        6
Orange County          6
Page County            6
Patrick County         6
Wyoming County         6
Name: count, Length: 188, dtype: int64

In [47]:
# Clean up text for aesthetic purposes
def clean_text(text):
    if isinstance(text, str):
        return text.title()  # Capitalizes the first letter of each word and makes the rest lowercase
    return text  # Return text unchanged if it's not a string

unemployment['County'] = unemployment['County'].apply(clean_text)

/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_12263/1939043739.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unemployment['County'] = unemployment['County'].apply(clean_text)

In [54]:
unemployment[unemployment['County'].str.contains('St. Louis')]

        FIPS Code      State            County  Unemployment rate  Year
141824      27137  Minnesota  St. Louis County                4.2  2000
141840      27137  Minnesota  St. Louis County                5.7  2004
141856      27137  Minnesota  St. Louis County                6.3  2008
141872      27137  Minnesota  St. Louis County                6.5  2012
141888      27137  Minnesota  St. Louis County                5.7  2016
141904      27137  Minnesota  St. Louis County                7.3  2020
161816      29189   Missouri  St. Louis County                3.0  2000
161832      29189   Missouri  St. Louis County                5.7  2004
161848      29189   Missouri  St. Louis County                6.1  2008
161864      29189   Missouri  St. Louis County                6.7  2012
161880      29189   Missouri  St. Louis County                4.2  2016
161896      29189   Missouri  St. Louis County                6.4  2020
163735      29510   Missouri    St. Louis City                5.4  2000
163751      29510   Missouri    St. Louis City                9.0  2004
163767      29510   Missouri    St. Louis City                7.9  2008
163783      29510   Missouri    St. Louis City                8.8  2012
163799      29510   Missouri    St. Louis City                5.4  2016
163815      29510   Missouri    St. Louis City                8.8  2020

In [60]:
import pandas as pd

# Define the expected 4-year interval years
expected_years = set(range(2000, 2021, 4))  # {2000, 2004, ..., 2020}

# Filter just the columns we need
subset = unemployment[['State', 'County', 'Year', 'Unemployment rate']]

# Remove rows where 'Unemployment Rate' is missing
subset = subset.dropna(subset=['Unemployment rate'])

# Group by county and collect available years
years_present = subset.groupby(['State', 'County'])['Year'].apply(set).reset_index()

# Find counties missing any expected year
years_present['Missing Years'] = years_present['Year'].apply(lambda y: expected_years - y)
counties_with_missing_years = years_present[years_present['Missing Years'].apply(len) > 0]

# Display the result
print("Counties missing data for at least one year:")
print(counties_with_missing_years[['State', 'County', 'Missing Years']])

Counties missing data for at least one year:
     State                 County       Missing Years
69  Alaska  Wrangell Borough/City  {2000, 2004, 2008}

Have to drop Alaska after all.

In [66]:
unemployment = unemployment[~unemployment['State'].str.contains('Alaska', na=False)]

In [67]:
unemployment

        FIPS Code    State          County  Unemployment rate  Year
201          1001  Alabama  Autauga County                4.1  2000
217          1001  Alabama  Autauga County                4.7  2004
233          1001  Alabama  Autauga County                5.3  2008
249          1001  Alabama  Autauga County                7.1  2012
265          1001  Alabama  Autauga County                5.1  2016
...           ...      ...             ...                ...   ...
322145      56045  Wyoming   Weston County                4.0  2004
322161      56045  Wyoming   Weston County                3.1  2008
322177      56045  Wyoming   Weston County                4.2  2012
322193      56045  Wyoming   Weston County                5.0  2016
322209      56045  Wyoming   Weston County                3.9  2020

[18678 rows x 5 columns]

In [68]:
unemployment[unemployment['State'].str.contains('Alaska')]

Empty DataFrame
Columns: [FIPS Code, State, County, Unemployment rate, Year]
Index: []

In [69]:
# Specify the desired file path (e.g., in a 'data' subfolder)
file_path = '/Users/matthewcavanaugh/Desktop/GitHub/us-presidential-elections-by-county/sources/Unemployment Cleaned.csv'

# Save the DataFrame to CSV at the specified path, without including the index
unemployment.to_csv(file_path, index=False)

# Income

In [72]:
income = pd.read_csv("/Users/matthewcavanaugh/Desktop/GitHub/us-presidential-elections-by-county/sources/Unemployment2023.csv")
income

,FIPS_Code,State,Area_Name,Attribute,Value
0,0,US,United States,Civilian_labor_force_2000,142601576.0
1,0,US,United States,Employed_2000,136904853.0
2,0,US,United States,Unemployed_2000,5696723.0
3,0,US,United States,Unemployment_rate_2000,4.0
4,0,US,United States,Civilian_labor_force_2001,143786537.0
...,...,...,...,...,...
329721,72153,PR,"Yauco Municipio, PR",Unemployment_rate_2022,10.3
329722,72153,PR,"Yauco Municipio, PR",Civilian_labor_force_2023,10488.0
329723,72153,PR,"Yauco Municipio, PR",Employed_2023,9278.0
329724,72153,PR,"Yauco Municipio, PR",Unemployed_2023,1210.0
329725,72153,PR,"Yauco Municipio, PR",Unemployment_rate_2023,11.5

In [74]:
income['Attribute'].value_counts()

Attribute
Unemployed_2021                              3273
Unemployment_rate_2023                       3273
Unemployed_2023                              3273
Employed_2023                                3273
Civilian_labor_force_2023                    3273
                                             ...
Unemployment_rate_2020                       3194
Unemployed_2020                              3194
Employed_2020                                3194
Civilian_labor_force_2020                    3194
Med_HH_Income_Percent_of_State_Total_2022    3194
Name: count, Length: 101, dtype: int64

In [76]:
income = income[income['Attribute'].str.contains('Income')]

In [77]:
income['Attribute'].value_counts()

Attribute
Median_Household_Income_2022                 3195
Med_HH_Income_Percent_of_State_Total_2022    3194
Name: count, dtype: int64

In [78]:
income

,FIPS_Code,State,Area_Name,Attribute,Value
96,0,US,United States,Median_Household_Income_2022,74755.0
193,1000,AL,Alabama,Median_Household_Income_2022,59703.0
194,1000,AL,Alabama,Med_HH_Income_Percent_of_State_Total_2022,100.0
294,1001,AL,"Autauga County, AL",Median_Household_Income_2022,70148.0
295,1001,AL,"Autauga County, AL",Med_HH_Income_Percent_of_State_Total_2022,117.5
...,...,...,...,...,...
322021,56041,WY,"Uinta County, WY",Med_HH_Income_Percent_of_State_Total_2022,102.5
322121,56043,WY,"Washakie County, WY",Median_Household_Income_2022,60699.0
322122,56043,WY,"Washakie County, WY",Med_HH_Income_Percent_of_State_Total_2022,85.2
322222,56045,WY,"Weston County, WY",Median_Household_Income_2022,67677.0
322223,56045,WY,"Weston County, WY",Med_HH_Income_Percent_of_State_Total_2022,95.0